= Information Technology

== The Internet of Things

The phrase "The internet of things" was first coined in 1999 by answering the question if it was possible to incorporate computer chips in electrical system to domestic appliances. +
Objects are identified via an IP address and are all connected to the Internet.
There are about 10 billion IoT devices for industrial, medical and commercial use at the moment.

== Reviews of IoT products

=== The OllieQ
OlliQ is an intelligent robot that will help older people to do online activities easily. Interact with people through small movements and it can also turn on and off lights.

=== The Furbo Camera
A robot that uses a camera to ejects dog treats on command via mobile app.

=== InstruMMents 01
A digital measuring tape in the shape of a pen connected via Bluetooth to your device. It also measure in 3D.

=== The Sherlock GPS bike tracker
A small device hidden inside your bike that can be tracked in case of theft.

=== The HAPIfork
An electronic fork that monitors and tracks your eating habits and it's useful for improving your eating behaviour.

== Generation Z rising

=== Meet Generation Z
Generation Z are the people who were born between 1995 and 2010. This generation comes after Millennials (born between 1980 and 1995), who lived in relative peace and economic prosperity.

=== Digital, social, visual
Most Gen Zs had a social media account since birth which they use to capture, post and share their lives with friends, family and followers. The most used platforms are YouTube and Facebook that, in many cases, replaced television.

=== A matter of privacy
The majority of Gen Z declared that their privacy is very important to them, in fact they tend to use anonymous social media platforms.

=== Gen-Z style
Unisex fashion is becoming more and more popular. It consists of combining outfits that don't match. +
They prefer to shop for clothes online rather than in physical stores.

== A matter of scale
In some cases desktop and laptops are not powerful enough for some operations, in this situations you may need a *workstation*. Workstations are used for expensive and sophisticated applications. +
The next level are the *mainframes* that can handle huge amounts of data in a serial way or in a parallel way. +
After the mainframe, there is the *supercomputer* that is bigger, faster and more expensive. Today supercomputers are used for weather maps, earthquake prediction and a lot of scientific operations.
