= Information Technology

== The Internet of Things
The phrase "The internet of things" was first coined in 1999 by answering the question if it was possible to incorporate computer chips in electrical system to domestic appliances. +
Objects are identified via an IP address and are all connected to the Internet.
There are about 10 billion IoT devices for industrial, medical and commercial use at the moment.

== Reviews of IoT products

=== The OllieQ
OlliQ is an intelligent robot that will help older people to do online activities easily. Interact with people through small movements and it can also turn on and off lights.

=== The Furbo Camera
A robot that uses a camera to ejects dog treats on command via mobile app.

=== InstruMMents 01
A digital measuring tape in the shape of a pen connected via Bluetooth to your device. It also measure in 3D.

=== The Sherlock GPS bike tracker
A small device hidden inside your bike that can be tracked in case of theft.

=== The HAPIfork
An electronic fork that monitors and tracks your eating habits and it's useful for improving your eating behaviour.

== Generation Z rising

=== Meet Generation Z
Generation Z are the people who were born between 1995 and 2010. This generation comes after Millennials (born between 1980 and 1995), who lived in relative peace and economic prosperity.

=== Digital, social, visual
Most Gen Zs had a social media account since birth which they use to capture, post and share their lives with friends, family and followers. The most used platforms are YouTube and Facebook that, in many cases, replaced television.

=== A matter of privacy
The majority of Gen Z declared that their privacy is very important to them, in fact they tend to use anonymous social media platforms.

=== Gen-Z style
Unisex fashion is becoming more and more popular. It consists of combining outfits that don't match. +
They prefer to shop for clothes online rather than in physical stores.

== A matter of scale
In some cases desktop and laptops are not powerful enough for some operations, in this situations you may need a *workstation*. Workstations are used for expensive and sophisticated applications. +
The next level are the *mainframes* that can handle huge amounts of data in a serial way or in a parallel way. +
After the mainframe, there is the *supercomputer* that is bigger, faster and more expensive. Today supercomputers are used for weather maps, earthquake prediction and a lot of scientific operations.

== Small, smaller, the smallest
Early computer enthusiasts used the *Altair 880*, where data and programs where both entered via switches on the front of the computer, and the programs were written in *Basic*,
then Apple 2 came in, it was a pc with *keyboard and display* that used *floppy discs*.
IBM then launched MS-DOS, but the need of portability led to the creation of *laptops* that had trackballs that were replaced with touchpads.

== The touchscreen revolution
They will be the future of computing, the *resistive systems* provides 2 layers of the screen, and when you touch it, the layers will make contact changing the electrical field, so the computer can locate where you clicked.
*Capacitive systems* use glass displays with a conductive layer, so when you touch the screen, some ofthe charge is transfered to your finger and the charge in that point of the screen decreases, so the computer will knows where you touched.
*Optical or infrared systems* are cheaper and better than the others touchscreen methods. The touch infact is registered as a shadow that passes through the optcal sensors.

== The new iPad 2018
It has a *retina display* with an amazing clarity and scratch-resistant glass, *touch id* to unlock it via your finger, *wi-fi and 4g lte* for a fast navigation on the internet, *augmented reality* that can help you in everyday problems like putting a furniture in your room and see how it fits.
It also has an *apple pencil* with a lot of functions, and *IOS* 11, the world most advanced mobile OS, that lets you run all the apps that you like, that are directly downloadable from the *app store*.

== The dark side of the Internet
The internet is a _public land_, and so it's not a perfectly safe place. +
Some hackers attack individuals, but most of them are not malicious. Their goal is to find holes in security systems. Penetrating one is known as an *exploit*. +
Crackers, instead try to create as much damage as possible. They might use *smurfing*, an attack that floods the ISP to block the flow of packets for customers. They might also use _malware_ like *viruses* to take over people's computers or *ransomwares* to demand money to restore their data.
Another negative side of the internet includes *spam*, email junk sent by companies for commercial purposes. They collect user's email addresses from public sources or by randomly guessing the usernames. +
This can be used also by *phishers*, whose goal is to trick people into giving sensitive information that they can then use or sell in black markets. For this they might end up using a *botnet*, a network of _zombie computers_ whose owners are unaware of their use, and that can be remotely controlled for anything.
Because this ends up being complicated, some criminals prefer *cybersquatting* which is the practice of registering a domain with a company's trademark, so that it will then be bought for much more.

== The anatomy of a phishing scan
A lot of people end up recieving phishing emails, but most of them have something in common:

- _Spelling and grammar_: it is very likely that the text contains some mistakes, as companies usually have a team whose job is to correct them.
- _Links_: it is always a good idea to not click on a link inside a suspicious message. By hovering on them you can preview where they'll redirect.
- _Threats_: a lot of these emails contain threats about your security and how it has been compromised.
- _Spoofed graphics_: there usually are images connected to legitimate companies that link to scam websites.

== Fake news
The term refers to news and stories that look real but are actually false and unfounded. Their clickbait gets people decieved and makes them share disinformation. +
Most people impulsively share fake news before they even had the time to check on the sources.
Bots might otherwise be used to share these news as if they were real people. Because of their wide spreading, they became one of the biggest internet problems.
There are a ton of websites that spread fake news. Most follow the style of legitimate news sites so that people get decieved easily without questioning. +
The authors might just be pressured by other news sites. As it usually is however, they might just do it for money, or even worse to change other's political beliefs.

== A guide to healthy computing
Because of the rapid changes in technology, computers are being used more and more for people's job. This might influece their performance and long-term health. +
This is why ergonomic devices were introduced. They help relax stress on muscles, thus reducing hands, wrists and eyes fatigue. +
Using well-designed tools is not enough though. Proper habits have to also be adopted to prevent injuries.

Because laptops are designed for portability, the keyboard and screen are connected, making them quite uncomfortable.
If you use it occasionally, you can just put in on your lap and tilt the screen back to minimize neck stress. But if you use it full-time, you should put it on your desk.
For this you might prefer to use a *laptop stand* to raise the laptop off the desk surface. +
The monitor height should be just below eye level, and the brightness should be adjusted to minimize the glare.
Taking visual breaks, changing posture and standing up from the chair for 15 minutes every now and then is one of the best methods to prevent health issues.

== You've got email
Email is one of the most important method of communication on the Internet. It is still widely used today as it's the preferred option for business. +
Each email program is expected to have the ability to send *attachments*, *save contacts* and send either a *carbon copy* (_Cc_) or a *blind copy* (_Bc_) which would be a copy of the email to other recipients.
Another special feature might be *tagging*, which allows to tag emails into categories.

Emails are sent to a mail server through a client. Most people now use *webmail*, so that they can access their emails from a browser.
These clients download all the emails from the server, when _IMAP_ is used, but only the new ones when _POP_ is used.

Because it's incredibly easy to use, a lot of people recieve *spam*. There are *spam filters* made to stop that, but it's not always enough. +
To make sure nobody reads your emails you can use *encryption*.

== Want to share news and opinions with the world?
Blogs are a simple way for users to share their thoughts on the Internet. Because of this, services to simplify the publishing of articles started to emerge all around the web.
The downside of using these tools is that they can be restrictive.

One way to overcome these issues is to build a *self-hosted* blog, so that everything can be customized.
In order to build one you must first register a *domain name*, and then get a server for the *hosting*. +
Free software, like _wordpress_ can be used to install a self-hosted blog, and tools like *FTP* allow the uploading of files to the server. For media, however, it might be cheaper to use sharing websites like YouTube because you won't be paying for the storage.

== Google sites
Google Sites is a website building platform that allows uses to create websites without knowing how to code. +
It supports choosing a theme, embedding of elements like maps and calendars and many other features, and limiting the access to a select few. If you don't own a domain name it will also allow you to buy one.

== Ready for a Twitter chat?
Twitter is like a blogging website that allows users to create posts of no more than 140 characters. In the early days it was thought as a limited platform for celebrities, but now everyone uses it.
Some people use it as a newsfeed, others as a microblog to update others about the work they're doing. +
A useful feature it provides is the filtering of what might not be of interest, given the amount of tweets you can have on your feed. +
Users can also be tagged by adding the 'at' character (@) before their username. If you want you can also write private messages called (DMs), though. Another special character is the 'hash' character that can categorize a tweet so as to make them easy to find.

== Facebook's privacy crisis
Mark Zuckerberg is the founder of one of the most famous social networks, Facebook. He recently faced a though privacy crisis.
The data of hundreds of millions of users has been illicitly obtained by Cambridge Analytica without the users' consent, and has been used to delude people to vote for Trump's presidential campaign. +
Because of this people are starting to realize how dangerous Facebook is. If you're concerned about your privacy there are some things you can do:

- Change the visibily of your profile from the settings
- Change what information is shared on Facebook
- Check your friends activity, so that you can remove tags of yourself if you want to
- Check for apps permissions

== Streaming media
*Streaming* is a way to listen to or watch media online without the need of *downloading* it which takes time and space. +
The first media which demonstrated the potential of streaming was Music, because of its compact _MP3_ format.

A user clicks on a link on a browser and it downloads a metafile. Thanks to this file the browser will start *buffering* the media the user requested and play it on a media player. +
This process will download parts of the file to save for later in order to play it without waiting times.

The most watched media comes from sites like _YouTube_, that also allow embedding the video on other websites or blogs.

== MP3: a popular audio file format
*MP3* stands for *MPEG 1 Audio Layer 3* and it's one of the most popular file formats to distribute music online since the mid-1990s. +

By using a *ripper* it's possible to convert the music source to _MP3_ and shrink it by a lot, while retaining CD-like quality.
You can choose how much information the music will lose during the *ecoding* and *compression* process. +
By changing the *bit rate* you can also tweak the compression rate, which tells how much data is required for one second of music.

The format stores music in a long string of binary numbers, which are separated into *frames*. At the start of the file there's the *metadata*, which contains information about the title, artist and genre.

These files can be copied into a portable _MP3_ player like the iPod. You can also burn them to a blank CD from your computer.

== Downloading music versus streaming music
Services like Amazon, Google Play or iTunes allow you to do save music on your device, which lets you listen to it without an active Internet connection. +
This however requires you to pay a *fee* for each song or album you download.

Streaming is different because you don't own the tracks and you have to use the WiFi or mobile data. Most services offer a free option with ads, otherwise you can pay and store music for offline listening too. +
They let you discover new and interesting music without having to pay too much for each track.

== Online gaming
One of the most enjoyable things to do with a computer network is to play *online games*. There are many ways to play them, from free games on the Internet to downloadable and boxed games for PCs and consoles.

*Single-player* and *multiplayer* games are the two main types of games. +
Most games now have an online element, which allows players to team up, fight against or simply chat with each other.

Many people believe online games represent a world of violence, and are usually blamed for things like failing grades at school or even cause acts of extreme violence. +
Research however, has shown that playing online games can be beneficial for your brain and they can have positive effects on people's social life.

Today, online gaming can be more than a hobby. There are now professional gamers (referred to as *pro gamers*) that turned gaming into a profession.
This includes competitions for all sorts of games which offer prizes in large sums of money.

== What is podcasting?
Not only did portable media players change the way we buy and listen to music, but also the way we listen to radio, via a technique called *podcasting*.
The word is a combination of "iPod" and "broadcast", because Apple made it easy to listen to them on the iPod.
With podcasts, anyone can create their own radio programme, and then people can subscribe to it to download it automatically on their iPods.

At first, it was more like a personal blog, but then the commercial world caught on. Today there are a lot of podcasts, ranging from people creating them in their living rooms to professional brodcasts from traditional radio stations. +
The recordings are saved in _MP3_ and then uploaded to a web server so that the _RSS feed_ can be created. This file can be edited manually or it can be automated by one of the many *podcast hosting sites*. These sites are useful when a person doesn't want to maintain their own server.

Subscribing to a podcast is a matter of downloading an _RSS reader_ and pasting the podcast URL. +
It's also possible to create a video podcast but that naturally requires more effort and equipment.
