= Information Technology

== The Internet of Things

The phrase "The internet of things" was first coined in 1999 by answering the question if it was possible to incorporate computer chips in electrical system to domestic appliances. +
Objects are identified via an IP address and are all connected to the Internet.
There are about 10 billion IoT devices for industrial, medical and commercial use at the moment.

== Reviews of IoT products

=== The OllieQ
OlliQ is an intelligent robot that will help older people to do online activities easily. Interact with people through small movements and it can also turn on and off lights.

=== The Furbo Camera
A robot that uses a camera to ejects dog treats on command via mobile app.

=== InstruMMents 01
A digital measuring tape in the shape of a pen connected via Bluetooth to your device. It also measure in 3D.

=== The Sherlock GPS bike tracker
A small device hidden inside your bike that can be tracked in case of theft.

=== The HAPIfork
An electronic fork that monitors and tracks your eating habits and it's useful for improving your eating behaviour.

== Generation Z rising

=== Meet Generation Z
Generation Z are the people who were born between 1995 and 2010. This generation comes after Millennials (born between 1980 and 1995), who lived in relative peace and economic prosperity.

=== Digital, social, visual
Most Gen Zs had a social media account since birth which they use to capture, post and share their lives with friends, family and followers. The most used platforms are YouTube and Facebook that, in many cases, replaced television.

=== A matter of privacy
The majority of Gen Z declared that their privacy is very important to them, in fact they tend to use anonymous social media platforms.

=== Gen-Z style
Unisex fashion is becoming more and more popular. It consists of combining outfits that don't match. +
They prefer to shop for clothes online rather than in physical stores.

== A matter of scale
In some cases desktop and laptops are not powerful enough for some operations, in this situations you may need a *workstation*. Workstations are used for expensive and sophisticated applications. +
The next level are the *mainframes* that can handle huge amounts of data in a serial way or in a parallel way. +
After the mainframe, there is the *supercomputer* that is bigger, faster and more expensive. Today supercomputers are used for weather maps, earthquake prediction and a lot of scientific operations.

== Small, smaller, the smallest
Early computer enthusiasts used the *Altair 880*, where data and programs where both entered via switches on the front of the computer, and the programs were written in *Basic*,
then Apple 2 came in, it was a pc with *keyboard and display* that used *floppy discs*.
IBM then launched MS-DOS, but the need of portability led to the creation of *laptops* that had trackballs that were replaced with touchpads.

== The touchscreen revolution
They will be the future of computing, the *resistive systems* provides 2 layers of the screen, and when you touch it, the layers will make contact changing the electrical field, so the computer can locate where you clicked.
*Capacitive systems* use glass displays with a conductive layer, so when you touch the screen, some ofthe charge is transfered to your finger and the charge in that point of the screen decreases, so the computer will knows where you touched.
*Optical or infrared systems* are cheaper and better than the others touchscreen methods. The touch infact is registered as a shadow that passes through the optcal sensors.

== The new iPad 2018
It has a *retina display* with an amazing clarity and scratch-resistant glass, *touch id* to unlock it via your finger, *wi-fi and 4g lte* for a fast navigation on the internet, *augmented reality* that can help you in everyday problems like putting a furniture in your room and see how it fits.
It also has an *apple pencil* with a lot of functions, and *IOS* 11, the world most advanced mobile OS, that lets you run all the apps that you like, that are directly downloadable from the *app store*.

== The dark side of the Internet
The internet is a _public land_, and so it's not a perfectly safe place. +
Some hackers attack individuals, but most of them are not malicious. Their goal is to find holes in security systems. Penetrating one is known as an *exploit*. +
Crackers, instead try to create as much damage as possible. They might use *smurfing*, an attack that floods the ISP to block the flow of packets for customers. They might also use _malware_ like *viruses* to take over people's computers or *ransomwares* to demand money to restore their data.
Another negative side of the internet includes *spam*, email junk sent by companies for commercial purposes. They collect user's email addresses from public sources or by randomly guessing the usernames. +
This can be used also by *phishers*, whose goal is to trick people into giving sensitive information that they can then use or sell in black markets. For this they might end up using a *botnet*, a network of _zombie computers_ whose owners are unaware of their use, and that can be remotely controlled for anything.
Because this ends up being complicated, some criminals prefer *cybersquatting* which is the practice of registering a domain with a company's trademark, so that it will then be bought for much more.
