= Azienda, Mercato e Organizzazione

== Microeconomia
L'economia si suddivide in: +

* *Microeconomia*: studia i singoli agenti economici (consumatori e imprese).
* *Macroeconomia*: studia grandi gruppi economici in generale.

L'*ipotesi di razionalità* è alla base della teoria economica dice che: si possono raggiungere i propri obiettivi con scarse risorse e che per raggiungerlo le persone cercano di ridurre al minimo l'utilizzo delle risorse.

Il *mercato* è l'istituzione economica che permette di acquistare e vendere beni e servizi.

Il *prezzo* viene definito dall'intersezione della curva di domanda e di quella di offerta.

I *fattori produttivi* sono le risorse impiegate nella produzione e sono: _lavoro_ e _capitale_.

La *domanda* è la quantità di un bene che viene richiesta dalle persone ad un certo prezzo. +
La curva di domanda presenta nell'asse y il *prezzo* e in x la *quantità domandata* e ha un andamento decrescente.

L'*offerta* è la quantità di bene che si è disposti a vendere ad un certo prezzo. +
La curva di ha in asse y il *prezzo* e in x la *quantità offerta* e ha un andamento crescente.

== I mercati
Le principali forme di mercato sono:

* *Concorrenza perfetta*: numero praticamente infinito di aziende, il prezzo non viene stabilito dall'azienda, i prodotti sono tutti molto simili tra loro, nessuna barriera di ingresso. (es. ortofrutta).

* *Concorrenza imperfetta*: un modesto numero di aziende, possono avere delle piccole modifiche sul prezzo modificando leggermente il prodotto iniziale, nessuna barriera di ingresso. (es. produttori di pasta).

* *Oligopolio*: poche aziende, offrono prodotto molto simili tra di loro, il prezzo viene stabilito dall'impresa. le barriere all'ingresso sono medio-alte. (es. smartphone).

* *Monopolio*: l'impresa è una, ha piena decisione del prezzo e della quantità del prodotto, le barriere all'ingresso sono molto forti. (es. tabacco, che è gestito dallo stato).

== Come trovare il prezzo di equilibrio
1. Avendo 2 equazioni del tipo: +
Q = 125 - 1,25p +
Q = 50 + 0,4p +
2. Mettere in egualianza le 2 equazioni: +
125 - 1.25p = 50 + 0.4p +
3. Ottenere il valore di p: +
p = *45,45* +
4. Per verificare che il prezzo sia di equilibrio mettere il valore di p nelle 2 equazioni che dovrebbero dare lo stesso risultato: +
Q = 125 - 1,25 * *45,45* = 68,18 +
Q = 50 + 0,4 * *45,45* = 68,18

== Il Break Even Point

Il *break Even Point* (BEP) è un valore che indica la quantità di merce da produrre per pareggiare i costi di produzione. +
Il BEP viene calcolato tramite la Break Even Analisys che può essere grafica o analitica (tabelle con valori). +
Tra i *vantaggi* principali troviamo: l'aiuto nelle previsioni, definizioni del prezzo e definizione dei costi. +
Lo *svantaggio* principale è che si tratta di un'analisi statica che deve essere ripetuta continuamente.

== Organizzazione Aziendale
L'organizzazione di un azienda è l'insieme delle persone che operano secondo policy, regole, procedure e coordinamento delle risorse.
La specializzazione del lavoro viene suddivisa in: +

* *Specializzazione verticale*: in cui le presone che progettano il lavoro e quelle che effettivamente eseguono il progetto sono *diverse*, quindi ogni persona ha solo un'attività da svolgere.

* *Specializzazione orizzontale*: in cui le persone possono svolgere compiti vari, quindi una persona può sia progettare che eseguire il progetto.

Per il coordinamento esistono 2 meccanismi:

* Meccanismi *ex-post*: in cui si organizza senza aver prima anticipato i problemi con relative soluzioni (se si incontra un problema si inveta una soluzione al momento).
* Meccanismi *ex-ante*: in cui l'organizzazione ha una progettazione a priori (i problemi più probabili hanno già una soluzione e una procedura per sistemarli).

*Posizione individuale*: è la posizione lavorativa che ricopre una persona. +
*Mansione*: è un inseme di compiti assegnati ad una _posizione Individuale_. +
*Compito*: è un inseme di attività collegate tra loro che non si possono suddividere. +
*Ruolo*: è l'insieme di aspettative che l'azienda si aspetta da un lavoratore. +
*Organigramma*: rappresentazione grafica della composizione dell'azienda con i rispettivi responsabili.

== Processi aziendali
Il processo aziendale è l'insieme di attività finalizzato alla creazione dell'output che verrà dato poi al cliente. +
Il cliente può essere sia esterno che interno (unità dell'azienda stessa).

Le fasi per la creazione del prodotto finale sono legate tra loro da delle *interdipendenze*:

* Sequenziali: l'output di una fase è l'input di un'altra.
* Reciproche: se due fasi producono un output che serve rispettivamente da input.
* Generiche: due fasi che condividono le stesse risorse.

Esistono 2 tipi di processi in un'organizzazione:

* *Processi primari*: concorrono alla creazione dell'output (vendità, marketing, pre-vendita, post-vendita, trasformazione di materie prime).
* *Processi di supporto*: sono necessari per il funzionamento dei processi primari.

Il *marketing* è classificabile in:

* marketing B2C: business to consumer.
* marketing B2B: business to business.

Il compito del marketing è quello di indirizzare il cliente a comprare un determinato prodotto, evidenziando gli aspetti migliori ma minimizzando i costi. Spesso per fare ciò il marketing fa leva sul *brand*

Il ciclo di vita del prodotto viene diviso in: *introduzione* (lancio del prodotto), *crescita* (aumento delle vendità), *maturità* (picco di vendite), *declino* (le vendite scarseggiano).
