= Giuseppe Ungaretti

Giuseppe Ungaretti nasce in Egitto nel 1888, nel 1912 si ferma in italia per studio. +
Lui era un interventista (voleva la guerra) per cui partecipa volontariamente alla prima guerra mondiale come soldato. La *guerra rappresenta un tema fondamentale* dei sui testi e la sua poetica. +
Durante la guerra lui scrive delle poesie durante le pause dal combattimento e si rende conto di quanto la guerra non fosse come immaginava ma era una totale assurdità.

La sua prima e la più importante raccolta si chiama *"L'Allegria"* che presenta una forte componente autobiografica dove racconta il suo periodo in Egitto e la prima guerra mondiale. +
La raccolta prende questo nome perchè lui ritiene che anche nei momenti peggiori come la guerra bisogna restare attaccati alla vita.

Lo stile di questa raccolta è:

* Abolizione della punteggiatura che sostituisce con gli spazi che rappresentano delle pause, ma conserva il punto interrogativo; (proveniente dai futuristi)
* Sostituisce le parole classiche quelle più comuni;
* Sconvolge la sintassi tradizionale, scrivendo parole senza connessione logica con le altre;
* Rifiuta le forme metriche tradizionali preferendo dei versi liberi: spesso composti da una sola parola; (proveninente dai simbolisti)

I temi sono:

* Le sofferenze che ha subito con la guerra;
* La morte, la solitudine e il dolore;
* La fratellanza tra gli uomini;
* Il desiderio di pace;

Alcuni brani di questa raccolta sono: "In memoria", "Veglia" e "Fratelli".

La seconda fase della vita di Ungaretti è rappresentata dalla raccolta "Sentimento del tempo" in cui tratta temi religiosi, di amore e di meditazione sulla morte.
Tratto da questa raccolta c'è la poesia "La madre".

Partecipa anche alla seconda guerra mondiale che segnerà un altro periodo della sua vita. Scrive infatti la raccolta *"Il dolore"* 
in cui racconta la sua sensazione di vuoto causata dalla perdita del fratello e del figlio di 9 anni e dalla seconda guerra mondiale. +
"Non gridate più" è un brano tratto dalla raccolta Il dolore.
