= Luigi Pirandello

== Vita

Luigi Pirandello nacque nel 1867 ad Agrigento, in Sicilia. Nel 1992 si trasferisce a Roma, in quel periodo seppur la corrente di scrittura principale era quella d'annunziana, Pirandello fu attratto piuttosto dalla corrente verista. +
Negli anni successivi Pirandello dovette affrontare un periodo di carenza economica e in più la malattia mentale della moglie, +
da questa situazione si ispirò molto per scrivere le sue opere e per capire il concetto della realtà: in cui non esite una realtà comune per tutti ma ognuno la vede a modo suo (la moglie non vedeva le cose come le vedeva lui). +
Con il passare del tempo si appassiona anche al teatro che lo aiutarono a vincere il premio Nobel per la letteratura. +
Morì nel 1936.

== Opere

Tra le sue opere più importanti troviamo: *"Fu Mattia Pascal"*, *"uno, nessuno e centomila"* e "l'esclusa". +

* *"Fu Mattia Pascal"* è sicuramente l'opera più famosa, scritta nel 1904, in cui racconta la storia di Mattia Pascal che dopo vari litigi con la moglie fugge da casa, casualmente vince una grassa somma di denaro al casinò, e mentre tornava a casa legge la notizie in cui si dice che lui sia morto. +
Approfitta di questa situazione per rifarsi una vita e da Mattia Pascal diventa Adriano Meis. La libertà che lui desiderava, però, è in realtà solo fittizia perchè non ha con sè dei documenti che identifichino che lui sia realmente Adriano Meis. Data la situazione, in cui si sente escluso e rifiutato, Adriano decide di fingere il suo suicidio e torna ad essere Mattia Pascal per riavere la sua vecchia vita. +
Tornando dalla moglie si accorge che si è sposata con un'altro e anche questa volta quello che gli rimane è il rifiuto, questa volta da parte della moglie. 

* *"Uno, nessuno e centomila"*, romanzo scritto nel 1926 racconta la storia di Vitangelo Moscarda che un giorno entra in crisi quando la moglie gli fa notare che il suo naso è storto, da questo fatto nascono delle sue considerazioni che lo portano a pensare che gli altri lo vedono in modo diverso da come lui vede se stesso. +
Dice inoltre che lui è *uno* per il modo in cui si vede, le immagini che gli altri hanno di lui sono *centomila* e dato che non è possibile dare un'identità univoca è anche *nessuno* (da questo deriva il nome dell'opera).  +
Infine, dopo una lunga serie di vicende il protagonista finisce per vivere da solo diventando un "nessuno". 
