= Luigi Pirandello

== Vita

Luigi Pirandello nacque nel 1867 ad Agrigento, in Sicilia. Nel 1992 si trasferisce a Roma, in quel periodo seppur la corrente di scrittura principale era quella d'annunziana, Pirandello fu attratto piuttosto dalla corrente verista. +
Negli anni successivi Pirandello dovette affrontare un periodo di carenza economica e in più la malattia mentale della moglie, +
da questa situazione si ispirò molto per scrivere le sue opere e per capire il concetto della realtà: in cui non esite una realtà comune per tutti ma ognuno la vede a modo suo (la moglie non vedeva le cose come le vedeva lui). +
Con il passare del tempo si appassiona anche al teatro che lo aiuterà a vincere il premio Nobel per la letteratura. +
Morì nel 1936.

== Poetica
Gli aspetti fondamentali della sua poetica sono principalmente due: il *concetto della maschera* e il *relativismo conoscitivo*. 

Secondo Pirandello ognuno di noi, per poter avere un ruolo nella società, deve indossare una *maschera* e interpretare un ruolo, per cui non esiste una comunicazione vera tra gli uomini. Solo attraverso la follia è possibile togliere la maschera e essere liberi. 

Da questa sua teoria nasce il suo *umorismo* tipico dei suoi testi: +
Pirandello scrisse un saggio nel 1908 chiamato "_L'umorismo_" in cui fa una differenza tra *comicità* e *umorismo* per poter capire la sua poetica, con *comicità* intende un fatto che è contrario a come ce lo aspettiamo e che ci porta alla risata, mentre definisce *umorismo* come una riflessione in cui vengono svelate delle realtà dolorose che si nascondono dietro al fatto comico. +
Inoltre chiama comicità come "avvertimento del contrario" e l'umorismo lo definisce "sentimento del contrario".

Per *relativismo conoscitivo* si intende che non esiste una verità oggettiva e valida per tutti, per cui la realtà è un punto di vista che dipende dalla persona che osserva.

Un altro principio su cui si basa la poetica di Pirandello è la differenza tra *vita* e *forma*, secondo cui la vita è un flusso incessante che noi cerchiamo di limitare in forme ben determinate, queste forme sono i nostri ideali oppure le convenzioni imposte dalla società.

Spesso i suoi personaggi sono isolati ed emarginati dalla società e la loro storie finiscono nella follia perchè cadono nelle trappole delle convenzioni sociali come la famiglia o il lavoro.

Utilizza uno stile poco ricercato e facilmente comprensibile utilizzando raramente dei termini dialettali o linguaggi tecnici.

== Opere

Tra le sue opere più importanti troviamo: *"Il fu Mattia Pascal"*, *"uno, nessuno e centomila"* e *"Novelle per un anno"*. +

* *"Il fu Mattia Pascal"* è sicuramente l'opera più famosa, scritta nel 1904, in cui racconta la storia di Mattia Pascal che dopo vari litigi con la moglie fugge da casa, casualmente vince una grassa somma di denaro al casinò, e mentre tornava a casa legge la notizie in cui si dice che lui sia morto. +
Approfitta di questa situazione per rifarsi una vita e da Mattia Pascal diventa Adriano Meis. La libertà che lui desiderava, però, è in realtà solo fittizia perchè non ha con sè dei documenti che identifichino che lui sia realmente Adriano Meis. Data la situazione, in cui si sente escluso e rifiutato, Adriano decide di fingere il suo suicidio e torna ad essere Mattia Pascal per riavere la sua vecchia vita. +
Tornando dalla moglie si accorge che si è sposata con un'altro e anche questa volta quello che gli rimane è il rifiuto, questa volta da parte della moglie. 

* *"Uno, nessuno e centomila"*, romanzo scritto nel 1926 racconta la storia di Vitangelo Moscarda che un giorno entra in crisi quando la moglie gli fa notare che il suo naso è storto, da questo fatto nascono delle sue considerazioni che lo portano a pensare che gli altri lo vedono in modo diverso da come lui vede se stesso. +
Dice inoltre che lui è *uno* per il modo in cui si vede, le immagini che gli altri hanno di lui sono *centomila* e dato che non è possibile dare un'identità univoca è anche *nessuno* (da questo deriva il nome dell'opera).  +
Infine, dopo una lunga serie di vicende il protagonista finisce per vivere da solo diventando un "nessuno".

* *"Novelle per un anno"* è una raccolta di novelle scritte da Pirandello composta da esattamente 365 novelle come i giorni in un anno. Ogni novella racconta una storia paradossale con le caratteristiche tipiche di pirandello: persone con grandi carichi di dolore, la follia, il relativismo conoscitivo e l'umorismo. +
Le due novelle che abbiamo trattato sono "La patente" e "Il treno ha fischiato...".

