= Ermetismo

La poesia degli *anni 30* è segnata dalla presenza dell'Ermetismo. +
Il termine Ermetismo fu utilizzato la prima volta dal critico *Francesco Flora* nel 1936 in un suo saggio letterario, definendolo come un insieme di esperienze poetiche caratterizzate dall'oscurità, cioè che erano difficili da comprendere e interpretare rispetto alle poesie del 1800/inizio 1900. Venne usato questo termine in riferimento a Ermes, dio greco. +
In questo suo saggio lui raggruppava nel termine Ermetismo la raccolta di Ungaretti "Il porto sepolto" e alcune poesie di Montale tra cui "Ossi di seppia".

Tra gli autori più rappresentativi di questo *movimento letterario italiano* troviamo: *Salvatore Quasimodo*, Mario Luzi e Alfonso Gatto. +
Il centro geografico dove si diffuse l'Ermetismo fu *Firenze*. +
L'Ermetismo per alcuni versi può rappresentare una esetensione del decadentismo, perche la situazione italiana si era aggravata ancora di più dopo la prima guerra mondiale e anche a causa della successiva dittatura fascista. Infatti i temi preponderanti sono interpretazione del dolore e della solitudine dell'uomo, la crisi della società e dei valori fondamentali. Questi temi vengono trattati molti più profondamente rispetto al decadentismo. +
Caratteristica importante dell'Ermetismo è il fatto che la poesia è *esclusivamente lirica*, cioè che mancano i toni umoristici e satirici, i temi civili, la politica che fino a inizio 1900 erano i temi principli. +
Inoltre la *poesia è estremamente breve* che rappresenta un momento improvviso che vive il poeta, rendendo così la poesia all'essenziale rendendola così difficile da comprendere.
