= Positivismo

Il positivismo si afferma principalmente nella seconda metà dell'Ottocento, epoca che dal punto di vista sociale ed economico è caratterizzata da:

* _Il progresso tecnologico e scientifico_, che porta poi all'industrializzazione
* _L'ascesa della borghesia liberale_, cioè le persone di classe media che impongono i miti del denaro e del profitto
* [[urbanesimo]]_L'urbanesimo_, che porta all'aumento del proletariato, cioè il trasfermiento di persone dalle campagne alle città per lavorare

Dal punto di vista filosofico invece, è caratterizzata dal *positivismo*.

'''

Il positivismo non è quella che si definisce una _corrente letteraria_ ma viene considerata una *corrente di pensiero* o *filosofica*. Questo significa che non ha influenzato lo stile e i contenuti degli scrittori, ma il modo di pensare delle persone.

Questo movimento celebra la scienza come strumento fondamentale di progresso e conoscenza, infatti afferma che la scienza può risolvere tutti i problemi dell'uomo. +
Al suo interno si distiguono:

* *Il positivismo sociale* di _Auguste Comte_ per cui scriverà un libro dove sostiene che:
** La scienza è l'unica forma di conoscenza possibile.
** Tutti i fenomeni sono in relazione tra loro (principio di causa ed effetto).
** L'unico metodo valido per l'indagine è quello sperimentale.

* *La teoria dell'evoluzione* di _Charles Darwin_ che grazie ai suoi libri sostiene che l'esistenza delle specie è caratterizzata da una continua lotta per la sopravvivenza, dove sopravvivono solo le specie più forti.

Grazie a questi principi la borghesia trova la conferma del suo *ottimismo* verso il progresso e gli permette di giustificare la *prevalenza* dei potenti sui più deboli.

== Naturalismo
Il positivismo portò delle conseguenze in ambito culturale e letterario, tra cui il _movimento letterario_ del *Naturalismo*.

Uno dei precursori del _Naturalismo_ fu _Honoré de Balzac_, che con il suo testo introdusse il movimento del _Realismo_. +
Questo movimento consisteva nell'analizzare scientificamente la realtà, per cui il pensiero non è più dominato dai principi astratti ma viene analizzato.

Al suo posto però, si affermò poi il _Naturalismo_ grazie al lavoro degli scrittori _Gustave Flaubert_ e i fratelli _Gon Court_. +
Questo portò all'affermazione di un'osservazione metodica della realtà e dal dare importanza alla parte di società più umile.

I principi del movimento vennero poi esposti ne **Il Romanzo Sperimentale** di _Émile Zola_, che sono:

* *Scientificità*: la scienza sperimentale viene usata per la scrittura dei romanzi, per cui i fatti devono essere analizzati. +
Questo cambiò il modo di descrivere l'uomo. Infatti non è più studiato l'uomo in astratto, ma l'uomo naturale influenzato dall'ambiente.
* *Impersonalità*: lo scrittore dev'essere oggettivo, e non deve intervenire personalmente.
* *Funzione sociale*: ha come scopo il miglioramento della società denunciandone i mali.

== Verismo
Il _Verismo_ è una _corrente letteraria_ che si sviluppa in *Italia* e viene considerata la *variante del Naturalismo* francese. +
Per via dello squilibrio tra il Nord e il Sud che, grazie all'xref:urbanesimo[aumento del proletariato] cresce ulteriormente, il _Versimo_ ha carattere regionale date le culture diverse delle regioni. +
Si diffose principalmente grazie al saggio scritto da _Pasquale Villari_, ma anche grazie al fastidio che i cittadini avevano verso quella che era la letteratura moderna.

Come il Naturalismo, anche il Verismo si basa sui principi esposti da _Émile Zola_. +
Al confronto del Naturalismo però, gli scrittori veristi non avevano lo stesso ottimismo di quelli francesi, infatti avevano una _visione pessimistica_. Non credevano nella funzione sociale dell'arte, e che quindi le condizioni dei più umili potessero cambiare.

_Luigi Capuana_, il principale scrittore del _Verismo_, scrisse *Il marchese di Roccaverdina*.
