= Germinie Lacerteux

In questo manifesto della poetica dei *Gon Court*, gli autori chiedono scusa ai lettori, in quanto andranno a leggere:

* storie tratte dalla _realtà delle classi inferiori_
* le miserie degli _umili e dei poveri_
* un _romanzo reale_ senza lieto fine

= Il marchese di Roccaverdina

Questo romanzo di *Luigi Capuana* narra quanto segue:

Il *marchese* convive da anni con una *contadina-amante* e per evitare una sua possibile unione matrimoniale, la fa sposare dal suo *fidato fattore* 
a patto che non abbia rapporti sessuali con ella.
Accecato dalla gelosia pensando che il fattore stia disobbidendo al marchese, quest'ultimo _uccise_ il suo fidato sottoposto, per poi far _incolpare un innocente_
che morirà in prigione.
Subito dopo il misfatto va dal prete a confessarsi giustificando il suo atto come una cosa che ritenenva corretta siccome il fattore non avrebbe dovuto comportarsi in certi modi.
Il brano si conclude con la visuale del marchese _in preda alla pazzia_ dovuta al rimorso dei suoi atti immorali. 
