= Verismo
Il _Verismo_ è una _corrente letteraria_ che si sviluppa in *Italia* e viene considerata la *variante del Naturalismo* francese. +
Per via dello squilibrio tra il Nord e il Sud che, grazie all'xref:urbanesimo[aumento del proletariato] cresce ulteriormente, il _Versimo_ ha carattere regionale date le culture diverse delle regioni. +
Si diffose principalmente grazie al saggio scritto da _Pasquale Villari_, ma anche grazie al fastidio che i cittadini avevano verso quella che era la letteratura moderna.

Come il Naturalismo, anche il Verismo si basa sui principi esposti da _Émile Zola_. +
Al confronto del Naturalismo però, gli scrittori veristi non avevano lo stesso ottimismo di quelli francesi, infatti avevano una _visione pessimistica_. Non credevano nella funzione sociale dell'arte, e che quindi le condizioni dei più umili potessero cambiare.

_Luigi Capuana_, il principale scrittore del _Verismo_, scrisse *Il marchese di Roccaverdina*.

== Giovanni Verga

In giovinezza era un giornalista politico e scriveva romanzi storico-risorgimentali come "I carbonari della montagna".

A Firenze conosce Capuana da cui si ispira per scrivere romanzi di ambientazione mondana. A Milano, invece, scopre gli autori del Naturalismo da qui si sviluppa il suo forte *pessimismo* e la sua *posizione politica reazionaria*, cioè contrario alla rivoluzione.

=== Periodo pre-verista

* *Romanzi storico-risorgimentali* in cui si intrecciano storie sentimentali alle storie politiche.
* *Romanzi mondani* con temi amorosi e psicologici caratterizzati da colpi di scena e suspance.
* *"Nedda"*: novella di rottura che porta Verga a *diventare un verista*. In questa novella tragica una ragazza povera viene messa incinta dal suo fidanzato che dopo pochi mesi muore in un incidente, la bambina nasce ma anche lei morirà a causa della fame.

In questa fase Verga non è ancora pienamente un verista perchè *utilizza commenti e giudizi* e non è presente il linguaggio proprio dei personaggi.

=== Periodo verista

I fattori che concorrono a formare la sua poetica sono tre: l'*evoluzionismo di Darwin* da cui deriva il senso della vita come lotta e il pensiero che nel progresso ci rimettano sempre i singoli, la *questione meridionale* in cui lui crede che sia inutile ribellarsi alle leggi, e infine il *Naturalismo* da cui deriva l'utilizzo dell'impersonalità.

=== I Malavoglia
È il primo romanzo appartenente al "ciclo dei vinti" di Verga. I protagonisti sono i membri della famiglia soprannominata "I Malavoglia". In questo romanzo la vita tranquilla della famiglia viene tempestata da una serie di sventure e tragedie.

Viene ritenuto un *romanzo corale* perchè tutto il paese gira intorno alla famiglia Malavoglia. In questo racconto si sentono le influenze della teoria dell'*evoluzione di Darwin* e il *tema dei vinti* in senso _privato_ in cui i malavoglia sono destinati ad essere vinti dai loro compaesani, e in senso _colletivo_ dove nel meridione i Borbone sono stati sostituiti dai Savoia.

* Lessico: Verga utilizza molte espressioni popolari come proverbi ed esclamazioni.
* Sintassi: si avvicina al dialetto perchè le sue frasi sono spesso indipendenti dalle altre e usa spesso il "che".
