= Giovanni Verga

In giovinezza era un giornalista politico e scriveva romanzi storico-risorgimentali come "I carbonari della montagna".

A Firenze conosce Capuana da cui si ispira per scrivere romanzi di ambientazione mondana come "Eva". A Milano, invece, scopre gli autori del Naturalismo da qui si sviluppa il suo forte *pessimismo* e la sua *posizione politica reazionaria*.

== Romanzi nel periodo pre-verista

- *Romanzi storico-risorgimentali* in cui si intrecciano storie sentimentali alle storie politiche.
- *Romanzi mondani* con temi amorosi e psicologici caratterizzati da colpi di scena e suspance che rispecchiano il gusto borghese.
- *"Nedda"*: novella di rottura che porta Verga a *diventare un verista*. In questa novella tragica una ragazza povera viene messa incinta dal suo fidanzato che dopo pochi mesi muore in un incidente, la bambina nasce ma anche lei morirà a causa della fame.

In questa fase Verga non è ancora pienamente un verista perche *utilizza commenti e giudizi* e non è presente il linguaggio proprio dei personaggi.
