= Brani

== Naturalismo

* *Questo romanzo è un romanzo vero* - fratelli Gon Court
+
In questa _prefazione del romanzo_ *Germinie Lacerteux* dei *Gon Court*, gli autori si rivolgono ai lettori chiedono scusa per quanto andranno a leggere, spiegando come il testo sia tratto dalla _realtà_ delle classi inferiori.

* *Osservazione e sperimentazione* - Émile Zola
+
Questo brano di *Émile Zola*, tratto da *Il Romanzo Sperimentale*, descrive come il compito del romanziere sia quello dell'_osservatore_, che si documenta sui fatti, e dello _sperimentatore_, che li sperimenta nel romanzo.

== Verismo

* *La confessione del marchese* - Luigi Capuana
+
Tratto da *Il marchese di Roccaverdina* di *Luigi Capuana* narra di un *marchese* che confessa di aver ucciso il marito della sua amante (il _fattore_) al prete, ma nonostante questo non vuole comunque auto denunciarsi. +
Finisce per preoccuparsi che il prete lo denunci, seguito da un rimorso per i suoi atti che lo portano alla _pazzia_.

* *La lupa* - Verga
+
Tratto dalla collezione di romanzi *Vita dei campi* di *Verga*, in cui adotta il principio dell'*Impersonalità*.
Il tema della collezione parla di come la società più umile non sia in grado di riscattarsi.
Il brano, invece, parla di una donna che, data la sua tendenza ad attirare i mariti altrui, viene chiamata _La Lupa_. Infatti attira anche il futuro marito della figlia, che però la preferisce a lei. +
Finisce quindi che per liberarsene il marito decide di ucciderla.

* *Prefazione* - Verga
+
Tratto da *I Malavoglia* narra di una famiglia che cercando di riscattarsi si avvicina sempre di più ad un fallimento (principio dell'ostrica).

* *L'arrivo e l'addio di 'Ntoni* - Verga
+
Tratto da *I Malavoglia* descrive il ritorno di 'Ntoni dopo 5 anni di prigione per contrabbando.
Tornando a casa scopre che il fratello minore ha riscattato la casa del nespolo (chiamata così data la sua vicinanza a tale albero).
'Ntoni si sente indegno di rimanerci dato il suo gesto criminale nel passato, il suo ritorno era solo un atto di nostalgia.

* *La famiglia Malavoglia* - Verga
+

