= Brani

== Naturalismo

* *Questo romanzo è un romanzo vero* - fratelli Gon Court
+
In questa _prefazione del romanzo_ *Germinie Lacerteux* dei *Gon Court*, gli autori si rivolgono ai lettori chiedono scusa per quanto andranno a leggere, spiegando come il testo sia tratto dalla _realtà_ delle classi inferiori.

* *Osservazione e sperimentazione* - Émile Zola
+
Questo brano di *Émile Zola*, tratto da *Il Romanzo Sperimentale*, descrive come il compito del romanziere sia quello dell'_osservatore_, che si documenta sui fatti, e dello _sperimentatore_, che li sperimenta nel romanzo.

== Verismo

* *La confessione del marchese* - Luigi Capuana
+
Tratto da *Il marchese di Roccaverdina* di *Luigi Capuana* narra di un *marchese* che confessa di aver ucciso il marito della sua amante (il _fattore_) al prete, ma nonostante questo non vuole comunque auto denunciarsi. +
Finisce per preoccuparsi che il prete lo denunci, seguito da un rimorso per i suoi atti che lo portano alla _pazzia_.

* *La lupa* - Verga
+
Tratto dalla collezione di romanzi *Vita dei campi* di *Verga*, in cui adotta il principio dell'*Impersonalità*.
Il tema della collezione parla di come la società più umile non sia in grado di riscattarsi.
Il brano, invece, parla di una donna che, data la sua tendenza ad attirare i mariti altrui, viene chiamata _La Lupa_. Infatti attira anche il futuro marito della figlia, che però la preferisce a lei. +
Finisce quindi che per liberarsene il marito decide di ucciderla.

* *Prefazione* - Verga
+
Tratto da *I Malavoglia* narra di una famiglia che cercando di riscattarsi si avvicina sempre di più ad un fallimento (principio dell'ostrica).

* *L'arrivo e l'addio di 'Ntoni* - Verga
+
Tratto da *I Malavoglia* descrive il ritorno di 'Ntoni dopo 5 anni di prigione per contrabbando.
Tornando a casa scopre che il fratello minore ha riscattato la casa del nespolo (chiamata così data la sua vicinanza a tale albero).
'Ntoni si sente indegno di rimanerci dato il suo gesto criminale nel passato, il suo ritorno era solo un atto di nostalgia.

* *La famiglia Malavoglia* - Verga
+
Il primo capitolo prevede una presentazione della famiglia Malavoglia, dove spiccano le figure di:
padron 'Ntoni, capo della famiglia, il figlio Bastianazzo e sua moglie Maruzza (la Longa).

* *L’addio alla roba* - Verga
+
Tratto da *Mastro-don Gesualdo*. Gesualdo ormai consapevole di morire va in preda allo sconforto e si trasferisce da sua figlia abbandonando la sua roba (beni accumulati negli anni di lavoro) e la sua serva fedele.

* *La morte di Gesualdo* - Verga
+
Tratto da *Mastro-don Gesualdo*. Nei suoi ultimi atti di vita Gesualdo è solo, circondato solo da oggetti preziosi. Come ultima richiesta chiede a sua figlia di dare del denaro alla famiglia della sua fedele serva ma il marito di sua figlia si oppone alla richiesta.

== Simbolismo

* *Spleen* - Charles Baudelaire
+
Brano tratto da *I fiori del male*: una raccolta di 100 liriche che trattano morte, ribellione e noia, questa raccolta porta un linguaggio totalmente nuovo in quel periodo. + 
Il significato di "Spleen" è la noia e il disgusto della quotidianità che suscitano nel poeta solitudine e malinconia, ciò lo porta a ribellarsi contro il mondo.

== Estetismo

//* *La pioggia nel pineto* - Gabriele D'Annunzio (11-29)
//* *Il ritratto di un esteta* - Gabriele D'Annunzio
//* *Il verso è tutto* - Gabriele D'Annunzio
//* *L'innocente: La rigenerazione spirituale* - Gabriele D'Annunzio
//* *Notturno: Deserto di cenere* - Gabriele D'Annunzio
