= Brani

== Naturalismo

* *Questo romanzo è un romanzo vero*
+
In questa _prefazione del romanzo_ *Germinie Lacerteux* dei *Gon Court*, gli autori si rivolgono ai lettori chiedono scusa per quanto andranno a leggere, spiegando come il testo sia tratto dalla _realtà_ delle classi inferiori.

* *Osservazione e sperimentazione*
+
Questo brano di *Émile Zola*, tratto da *Il Romanzo Sperimentale*, descrive come il compito del romanziere sia quello dell'_osservatore_, che si documenta sui fatti, e dello _sperimentatore_, che li sperimenta nel romanzo.

== Verismo

* *La confessione del marchese*
+
Tratto da *Il marchese di Roccaverdina* di *Luigi Capuana* narra di un *marchese* che confessa di aver ucciso il marito della sua amante (il _fattore_) al prete, ma nonostante questo non vuole comunque auto denunciarsi. +
Finisce per preoccuparsi che il prete lo denunci, seguito da un rimorso per i suoi atti che lo portano alla _pazzia_.

* *La lupa*
+
Tratto dalla collezione di romanzi *Vita dei campi* di *Verga*, in cui adotta il principio dell'*Impersonalità*.
Il tema della collezione parla di come la società più umile non sia in grado di riscattarsi.
Il brano, invece, parla di una donna che, data la sua tendenza ad attirare i mariti altrui, viene chiamata _La Lupa_. Infatti attira anche il futuro marito della figlia, che però la preferisce a lei. +
Finisce quindi che per liberarsene il marito decide di ucciderla.
