= Il Decadentismo

== Crisi del Positivismo
Verso la fine del 1800 si presenta una crisi del Positivismo in cui nascono culture che hanno in comune solo il *rifiuto delle certezze scentifiche* e la tendenza all'irrazionalità (agire senza pensare).

I più importanti esponenti di fine 1800 sono:

* Friedrich Nietzsche [Nice]: *rifiuta* e abbatte tutte le teorie della *scienza, della religione e della morale* che ritiene appartenenti all'uomo tradizionale e secondo lui bisognerebbe dar vita al *Superuomo* (l'incarnazione della volontà di potenza) caratterizzato da aggressività, istinto, gioco e spirito di creazione. +
Le sue idee venivano monipolate come prese di posizione anti-democratiche (nazismo).

* Henri Bergson: per lui la *vita è creazione* che si evolve nel tempo e sostiene che soltanto attraverso l'intuizione è possibile cogliere il vero significato della vita e delle cose.

== Simbolismo
Movimento letterario nato in Francia che interpreta la crisi del Positivismo. +
Il precursore del Simbolismo è *Charles Bodler* con la sua poesia "Corrispondenze". +
I temi per cui anticipa il Simbolismo sono:

* Che la *realtà è un mistero* che si può scoprire solo attraverso l'arte e la poesia.
* Che nella realtà esistono corrispondenze tra colori (vista), suoni (udito), e profumi (olfatto), da cui deriva l'uso di sinestesie (odori freschi, profuni dolci).
* Esalta i sensi e gli aspetti dell'animo irrazzionale dell'uomo (inconscio).
