= Il Decadentismo

== Crisi del Positivismo
Verso la fine del 1800 si presenta una crisi del Positivismo in cui nascono culture che hanno in comune solo il *rifiuto delle certezze scentifiche* e la tendenza all'irrazionalità (agire senza pensare).

I più importanti esponenti di fine 1800 sono:

* Friedrich Nietzsche [Nice]: *rifiuta* e abbatte tutte le teorie della *scienza, della religione e della morale* che ritiene appartenenti all'uomo tradizionale e secondo lui bisognerebbe dar vita al *Superuomo* (l'incarnazione della volontà di potenza) caratterizzato da aggressività, istinto, gioco e spirito di creazione. +
Le sue idee venivano monipolate come prese di posizione anti-democratiche (nazismo).

* Henri Bergson: per lui la *vita è creazione* che si evolve nel tempo e sostiene che soltanto attraverso l'intuizione è possibile cogliere il vero significato della vita e delle cose.

== Simbolismo
Movimento letterario nato in Francia che interpreta la crisi del Positivismo. +
Il precursore del Simbolismo è *Charles Bodler* con la sua poesia "Corrispondenze". +
I temi per cui anticipa il Simbolismo sono:

* Che la *realtà è un mistero* che si può scoprire solo attraverso l'arte e la poesia.
* Che nella realtà esistono corrispondenze tra colori (vista), suoni (udito), e profumi (olfatto), da cui deriva l'uso di sinestesie (odori freschi, profuni dolci).
* Esalta i sensi e gli aspetti dell'animo irrazionale dell'uomo (inconscio).

Oltre a questi punti le caratteristiche del simbolismo comprendono: 

* La critica verso i borghesi.
* Anticonformismo (andare contro corrente, non seguire la massa).
* Rifiuto del progresso.
* Un linguaggio che fa riferimento a immagini (da cui deriva il nome Simbolismo).

I più importanti *rappresentanti del Simbolismo* sono: Paul Verlaine, Arthur Rimbaud e Stéphane Mallarmé (chiamati i poeti maledetti). +
Secondo loro il *poeta* ha il ruolo di *veggente* che attraverso l'intuizione e la poesia può scoprire i misteri della vita e della natura.

== Inizio del 1900
In questo periodo nascono *tre nuove teorie scientifiche* che segnano l'inizio di una nuova epoca.

* *Freud*: medico austriaco che pubblica "l'interpretazione dei sogni" e fonda i *principi della psicoanalisi* (tecniche per analizzare e far riemergere ricordi profondi nelle persone) in cui si mettono a paragone il _superio_ che rappresenta il senso morale, il _es_ che rappresenta l'istinto, e l'_io_ che è un mediatore tra _es_ e il _superio_. +
l'_es_ e il _superio_ sono in continua lotta e l'_io_ bilancia questa lotta.

* *Einstein*: fisico che presenta la *teoria della relatività* che porta al superamento della fisica classica di Newton e Galileo. Questa teoria stabilisce l'equivalenza tra massa ed energia.

* *Wllian james*: filosofo e psicologo americano che scrive "principi di psicologia" in cui sostiene che nelle teorie etiche e *religiose nulla è certo* e dimostrabile, e dice che bisogna credere a ciò che ci è utile senza pretendere una verità assoluta (filosofia che si chiama "pragmatismo"). + 
Nazismo e Fascismo utilizzano questa teoria per giustificare le proprie azioni.



