= Estetismo

Movimento artistico nato in Inghilterra a fine 1800. +
Il principio alla base dell'Estetismo è *l'arte per l'arte* cioè utilizzare l'arte per esaltare la bellezza dell'arte stessa. Secondo questo movimento l'arte rifiutava la morale comune e non doveva avere scopi politici. +
Gli artisti dovevano trasformare la propria vita in una forma d'arte creando così la figura dell'*esteta* che ha come obiettivo quello di ricercare uno stile di vita raffinato e nobile.

I principali esponenti dell'Esetetismo sono: Gabriele D'Annunzio (italiano) e Oscar Wild (Inglese).

== Gabriele D'Annunzio

Nasce a Pescara (Abruzzo) nel 1863, vive una vita aristocratica piena di storie d'amore girando tutta italia, fino ad arrivare anche in politica. +
Questa vita lo porta ad indebitarsi e quindi decide di scappare in Francia, tornerà in italia solo dopo l'inizio della prima guerra mondiale, dove inizia a scrivere i suoi testi più importanti e a compiere grandi imprese come: il "volo su Vienna" la "beffa di Buccari", la "vittoria mutilata" e l'occupazione della città di Fiume. +
Appartiene alla corrente dell'estetismo mettendo in pratica il concetto di vivere una vita inimitabile piena di sfizi e ricchezze e in cui si sente superiore a tutti.
D'Annunzio deriva il concetto di superuomo di Nice perche lui si sente un privilegiato che può manipolare il popolo.
