= Futurismo
Con *"Avanguardie storiche"* si intendono movimenti culturali e artistici che hanno in comune il rompere gli schemi artistici tradizionali, l'espansione di questi movimenti fu
accellerato dall'avvento del cinema, della radio e della fotografia.

Il *futurismo* fu un movimento di avanguardia fondato da *Marinetti* a Parigi nel 1909 dopo la pubblicazione di un manivesto in un giornale Francese. +
I futuristi derivano questo nome al fatto che videro nelle macchine e nella *tecnologia il futuro del mondo* e disprezzavano tutto quello che apparteneva al passato, come la borghesia. +
Essi erano *favorevoli alla guerra* (e al Fascismo) in quanto ritenevano che portava un progresso nella società; rifiutavano anche la razionalità preferendo l'*intuito*.

Il futurismo comprende ogni tipo di arte: dalla musica, alla pittura, alla letteratura fino alla moda.

== La letteratura futuristica

Secondo loro bisognava *distruggere la sintassi*, abolendo l'avverbio e la punteggiatura, e usando i verbi all'infinito. +
Quindi non si ha più una scrittura letta da sinistra verso destra con una riga sotto l'altra, ma le parole vengono sparse per il foglio.

Gli esponenti letterari più importanti sono: *Marinetti* e *Palazzeschi*.
