= Positivismo

Il positivismo si afferma principalmente nella seconda metà dell'Ottocento, epoca che dal punto di vista sociale ed economico è caratterizzata da:

* _Il progresso tecnologico e scientifico_, che porta poi all'industrializzazione
* _L'ascesa della borghesia liberale_, cioè le persone di classe media che impongono i miti del denaro e del profitto
* _L'urbanesimo_, cioè il trasfermiento di persone dalle campagne alle città più grandi

Dal punto di vista filosofico invece, è caratterizzata dal *positivismo*.

'''

Il positivismo non è quella che si definisce una _corrente letteraria_ ma viene considerata una *corrente di pensiero* o *filosofica*. Questo significa che non ha influenzato lo stile e i contenuti degli scrittori, ma il modo di pensare delle persone.

Questo movimento celebra la scienza come strumento fondamentale di progresso e conoscenza, infatti afferma che la scienza può risolvere tutti i problemi dell'uomo. +
Al suo interno si distiguono:

* *Il positivismo sociale* di _Auguste Comte_ per cui scriverà un libro dove sostiene che:
** La scienza è l'unica forma di conoscenza possibile.
** Tutti i fenomeni sono in relazione tra loro (principio di causa ed effetto).
** L'unico metodo valido per l'indagine è quello sperimentale.

* *La teoria dell'evoluzione* di _Charles Darwin_ che grazie ai suoi libri sostiene che l'esistenza delle specie è caratterizzata da una continua lotta per la sopravvivenza, dove sopravvivono solo le specie più forti.

Grazie a questi principi la borghesia trova la conferma del suo ottimismo verso il progresso e gli permette di giustificare la prevalenza dei potenti sui più deboli.
