= Il Fascismo

== Contesto storico
Alla fine della guerra l'Italia è in una situazione economica disastrosa dove il salario di un operaio era appena raddopiato mentre i prezzi degli alimentari era aumentato di 6 volte.

Nel *1919* la gente scende nelle piazze a protestare, e sempre in quel periodo nascono i primi fasci di combattimento assieme alle prime camice nere.
Nel *1920* dopo vari scioperi e proteste vengono anche occupate le fabbriche, un evento che poertò alla creazione del partito comunista italiano nel *1921*.

La sinistra lottava perchè la classe contadina operaia arrivasse al potere mentre la destra, che era nazionalista ed era ancora combattuta per non aver ricevuto la Dalmazia dopo la guerra, lo voleva evitare, conferendo così più potere alle classi privilegiate, tra cui la borghesia che desiderava un governo forte.

Le camice nere usavano la violenza per combattere il comunismo e i sindacati, e cominciavano ad essere viste con tolleranza sopratutto dagli industriali, usati come un mezzo per mettere a tacere i braccianti.

Nel *1921 nasce il partito fascista di Mussolini*, il quale nel suo primo anno prende 45 seggi che lo aiuteranno poi con il suo colpo di stato.

Il partito fascista è sostenuto da:

* Industriali del nord che lo favorivano per incutere paura e quindi evitare proteste operaie.
* Gli ufficiali che aspirano ad una rivincita nazionalistica. 
* La borghesia che voleva migliorare le proprie condizioni economiche.

Lo _sciopero generale_ fatto dalla sinistra fallì miseramente portando ad altre violenze da parte delle camice nere, ed è proprio in questo momento che Mussolini decide che era arrivato il momento di prendere il potere. 

== L'ascesa del fascismo in Italia
Il *28 ottobre 1922* le camice nere marciano su Roma ed il re _Vittorio Emanuele terzo_ non le fa disperdere, ed inoltre rende Mussolini primo ministro, inizia qui il governo fascista che durò per 20 anni (fino a luglio 1943).

Mentre il Nazismo è arriverà al potere per vie legali, il Fascismo ci è arrivato per via di un colpo di stato.

Inizialmente il partito di Mussolini non era una dittatura, questo per non andare contro a chi lo sosteneva, si pensava inoltre che il fascismo sarebbe stato un governo provvisorio e che sarebbe durato finchè non si sarebbe rispristinato l'ordine nella società (dato che c'erano molte proteste e scioperi).

Nel *1924* si tennero le elezioni ma Mussolini si era garantito la vittoria facendo approvare una lgge elettorale per cui il partito che avesse percepito il 25% dei voti si sarebbe preso il 75% dei seggi e grazie a questo il fascismo aveva 403 deputati contro 106 dell'opposizione.

Gli italiani dicevano ancora no al fascismo, allora i fascisti passarono a metodi ancora più brutali come *l'omicidio di Matteotti nel giugno del 1924*.

== Giacomo Matteotti

Vittima del Fascismo e anche oppositore, diventò un socialsita dopo aver assistito alle ingiustizie locali risalenti al periodo dal 1882 al 1885, dove c'erano molti scioperi nel polesine (terra natale di Matteotti) che sebbene facevano aumentare le paghe, facevano anche arrestare delle persone che protestavano.
Matteotti si laurea in legge assumendo cariche rilevanti tra cui deputato e da tale riuscì a migliorare le condizioni dei contadini, definiva vergognosa _l'alleanza tra proprietari terrieri ed i fascisti_, inoltre condannava gli _abusi di Mussolini ed i suoi sottoposti_, la _mancanza di diritto allo scipero_ assieme ad il fatto che _tutti sottostavano ai fascisti_. 

Nella *primavera del 1924* inizia la _campagna elettorale costellata di episodi di violenza_, che portò il fascismo a vincere con il 64% dei voti perciò fu chiaro che la vittoria era "taroccata" dato che gli italiani si stavano rendendo conto delle azioni di Mussolini.
Il 30 maggio Matteotti va in parlamento per denunciare le ingiustizie protratte da Mussolini, voleva per giunta che le elezioni venissero sospese dato che il popolo italiano non aveva votato con piena libertà.

Matteotti 10 giorni dopo sparì assieme la sua valigetta fornita dagli inglesi, contenente tutte le prove della corruzzione fascista, 2 mesi dopo venne trovato il suo cadavere in un bosco.
Il Fascismo perse una parte di consenso dagli italiani, gli esecutori dell'omicidio vennero arrestati, ma poco dopo con la corruzione fascista gli esecutori vennero scarcerati in breve tempo.

== La presa al potere di Mussolini
Mussolini vuole fare del suo partito l'organismo principale dello stato e quindi della sua dittatura, per far ciò abbandona ogni forma di legalità, tanto che nel *1925* nascono _leggi fascistissime_ che aboliscono libertà democratiche e resero illegale ogni opinione antifascista.
Tra i cambiamenti drastici effettuati in quel periodo ricordiamo:

* Le camice nere ora riconosciute milizia per la sicurezza nazionale, avevano il compito di testare la fede fascista dei cittadini.
* Venne resa obbligatoria l'iscrizione al partito fascista per partecipare ai concorsi pubblici ed esercitare molte professioni.
* Venne abolito il segreto di voto dato che per votare bisognava scegliere tra una scheda con il tricolore oppure una grigia, rendendo riconoscibili le persone che votoavano contro il partito (per poi picchiarle).

Un grande successo che procurò al regime fascista l'appoggio della Chiesa fu la firma dei *patti lateranensi* nel *1929*, i quali comprendevano che:

* Il vaticano sarebbe stato riconosciuto come stato indipendente
* Il riconoscimento del cattolicesimo come religione di stato
* L'insegnamento della religione cattolica nelle scuole
* Il matrimonio religioso assunse valore civile (trascritto in comune)
* Vantaggi del clero come gli stipendi 

Il parlamento venne sostituito dalla *camera dei fasci e delle corporazioni* che potevano solo _dare consigli_ sulle leggi, per corporazioni si indicano le istituzione del lavoro, garantendosi l'appoggio degli industriali, inoltre venivano eletti *gerarchi e federali* i quali compivano il volere del duce.
Nel *1933* venne fondato l'*IRI* (istituto per la ricostruzione industriale), un ente che aiutava le industrie in difficoltà a causa della crisi economica.

== Alineamento con la politica di Hitler
Nel *1938* Mussolini proclama il *manifesto della razza* dove limita la libertà degli ebrei presenti in Italia, il quale affermava che:

* Esistevano razze superiori
* La razza italiana era prevalentemente ariana
* Gli italiani dovevano dichiararsi razzisti
