= Il dopoguerra

La prima guerra mondiale era stata molto vantaggiosa economicamente e tecnologicamente per gli stati uniti, tanto da farla diventare la prima potenza industriale del mondo. +
Gli americani pensavano di aver trovato la formula per la prosperità: chi aveva capacità e intraprendenza poteva diventare ricco, questo portava molta concorrenza
tra le industrie. Lo stato doveva solo mettere alte tasse doganali (sui prodotti esteri) in modo da proteggere il mercato interno e favorire la *libera competizione* dei mercati.

Furono approvante anche delle leggi che limitavano l'immigrazione dall'Europa e iniziarono a diffondersi idee xenofobe e razziste nei confronti degli europei (Ku Klux Klan) +
Ci fu anche il periodo del *proibizionismo* che proibiva il commercio degli alcolici da parte della gente di colore, questo porta a situazioni di gangsterismo da parte degli immigrati in america che distribuiscono alcool illegalmente e seminano il panico per marcare il loro territorio. +
Questa situazione portò il presidente Roosevelt a dover abolire il proibizionismo.

== La grande crisi

Il mercato industriale si stava evolvendo molto velocemente (soprattutto quello automobilistico) il problema era che poca gente aveva il potere di acqusto per permettersi quei beni.
Dato lo squilibrio tra produzione e vendita, improvvisamente tutti volevano ritirare le proprie azioni in borsa prima che il loro valore crollasse. +
A Wall Street il 24 ottobre 1929 ("giovedì nero") vennero messe all'asta contemporamentente 13 milioni di azioni, di conseguenza il loro valore crollò vertiginosamente: questo fu l'inizio della più grande crisi economica della storia (chiamata "Grande depressione") che si espanse anche in europa (favorendo nazismo e fascismo) e che continuò fino al 1932.

== La Rinascita dell'economia

Roosevelt riuscì a imporre all'economia un nuovo orientamento chiamato _New Deal_ il cui obiettivo era quello di *rilanciare la produzione* incrementando i consumi,
e quindi di cambiare il ruolo dello stato nell'ambito economico: ora lo stato si occupava da più vicino dell'economia (per esempio regolando le banche). +
Roosevelt combattè la disocupazione attraverso lavori pubblici portando le persone ad ottenere potere di acquisto che serviva per far ripartire l'industria.

Questo _New Deal_ portò grande successo e apprezzamento a Roosevelt che rimase in carica fino alla sua morte.

== Economia pianificata e di mercato

L'economia pianificata e di mercato erano i principali modelli economici del 1900 a cui si aggiungi anche l'economia mista. +
*Economia di mercato* (sistema capitalistico): sostiene la libertà di impresa e di mercato ed è presente la libera concorrenza tra le imprese. +
*Economia pianficata*: in cui l'economia è sotto al controllo dello stato (applicata in Russia). +
*Economia mista*: (modello economico elaborato da Keynes) che rappresenta una via di mezzo tra le 2 economie, mantenendo il libero mercato ma con un parziale intervento dello stato (tecnica applicata da Roosevelt nel _New Deal_).
