= Nazismo

In Germania nel 1919 viene eletta con suffragio universale un'assemblea per elaborare una nuova repubblica democratica che si chiamerà _repubblica di Weimar_. Venne eletto anche il presidente di questa repubblica che deteneva un potere di nominare il *cancelliere* (il capo del governo). +
Tra il 1921 e il 1923 in Germania scoppia una grande inflazione (il valore della moneta [il _marco_] calò moltissimo), a causa di questo molte persone si impoverirono, ed altre persone la cui ricchezza non dipendeva dal denaro (gli industriali) diventarono più ricche, questo fece crescere consensi nella destra (i conservatori e nazionalisti). +
Il fatto che portò al potere l'estrema destra (il Nazismo) fu la crisi degli Stati Uniti.
*Hitler* approfitta della crisi e va a capo del partito nazionalsocialista o *Partito Nazista* che nel 1932 diventa il partito di maggioranza e, nel 1933 il presidente della repubblica Hindenburg nomina *Hitler cancelliere*.

== Il programma politico di Hitler

Il programma di gestione della Germania è molto rigido e vilento: +
Hitler organizza le _SA_ che sono le forze di assalto che avevano lo scopo di intimorire con la violenza gli oppositori (la sinistra, il socialismo). +
Era anche convinto che esistesse una razza superiore, la *razza ariana*, di cui facevano parte i tedeschi. Hilter sosteneva che questa razza dovesse dominare le razze inferiori come gli slavi (accusati di occupare lo spazio della germania) e soprattutto gli *ebrei* che li ritenevano responsabili dei mali del mondo come il comunismo e il capitalismo. + 
Questi ideali vengono condivisi da moltissime persone e soprattutto dagli industriali (perche i nazisti frenavano le proteste degli operai) i quali sostengono economicamente lo sviluppo del Nazismo.

Apppena arrivato al potere Hitler (per dare prova della sua forza) diede fuoco al _reichstag_ (il parlamento) dando la colpa ai comunisti; venne abolita la libertà di stampa; i sindacati (coloro che difendono i diritti dei lavoratori) furono sciolti; venne istituita la pena di morte. +
Quando il presidente Hindenburg morì Hitler assunse tutti i poteri con il titolo di *Führer* (duce). +
A questo punto per gli oppositori politici fu aperto il primo campo di concentramento, e iniziarono le persecuzioni contro gli ebrei togliendo loro ogni tipo di diritto. +
Vengono organizzate anche le _SS_ che sono le squadre di protezione di Hitler. +
Venne istitutita la *Gestapo*, una polizia segreta dello stato che individuava ebrei e oppositori. +
Anche le scuole e le religioni subirono dei cambiamenti obbligando le persone ad obbedire agli ideali nazisti.

In questo modo Hilter obbligò così tutti ad essere favorevoli al Nazismo.
