= Espansione dei regimi autoritari

Nel 1933 Germania e Giappone uscirono dalla *Società delle Nazioni* (Oragnizzazione con lo scopo di accrescere la qualità della vita degli esseri umani), successivamente nel 1937 uscirà anche l'Italia. questi tre paesi infatti pensavano, diversamente dagli altri paesi, che i problemi tra nazioni si potessero risolvere con le armi. +
Mentre L'Italia e la Germania erano rispettivamente Fasciste e Naziste non c'è da stupirsi per questo loro atteggiamento, per quanto riguarda il Giappone, dal 1930 era comandato da un governo autoritario con a capo l'imperatore Hirohito. +
Questo imperatore aveva favorito l'ascesa al potere dei militari che eliminarono i partiti politici avversari, in più vollero espandersi occupando una regione della Cina, la Manciuria. Così a seguito delle proteste da parte della Società delle Nazioni il Giappone decise di lasciarlo.

Questo desiderio di espansione era tipico dei paesi fascisti/nazisti infatti l'Italia non contenta di possedere Libia, Eritrea e Somalia, e a seguito del blocco di emigrazione verso gli Stati Uniti, Mussolini nel 1935 ordina di occupare l'Etiopia. L'occupazione ebbe un facile successo data la differenza delle potenze militari dei due paesi. +
L'occupazione dell'Etiopia, che faceva parte della Società delle Nazione, portò l'Italia a subire delle sanzioni economiche e i membri della Società non avrebbero più commerciato con l'Italia (in realtà alcuni paesi continuarono a farlo, per cui l'Italia non soffrì così tanto questi provvedimenti).
L'Italia combatterà poi le decisioni prese dalla Società delle Nazioni con *l'autarchia* (sfruttare le proprie risorse rendendo così il proprio stato indipendente dagli altri).

La Guerra fatta in Etiopia dimostrò a Hitler e Mussolini che avrebbero potuto proseguire le loro espansioni aggressivamente senza essere puniti.
Hitler infatti nel 1936 invade la Renania e il legame con l'Italia diventa sempre più forte, tanto che firmano un trattato di alleanza contro la Russia, chiamato *Asse Roma-Berlino*. 
L'anno successivo l'alleanza si estende al Giappone diventando *Asse Roma-Berlino-Tokyo*, questo porta il Giappone a scatenare una guerra contro la Cina, e Hitler decide di invadere l'Austria annettendola sotto il dominio tedesco, invade anche i Sudeti (una zona della Cecoslovacchia) per poi invadere tutta la Cecoslovacchia, con la scusa che in quella zona si parlava tedesco.
Gli italiani sbarcheranno invece in Albania, spodestando il re albanese e proclamando Vittorio Emanuale III re di Albania.

Mussolini e Hitler stringono una nuova alleanza, il *Patto d'Acciaio*, nel 1939, in cui l'Italia doveva combattere a fianco della Germania in caso di guerra.
Viene poi fatto un patto tra Germania e Unione Sovietica che prevedeva la spartizione della Polonia tra i due paesi.
