= Seconda guerra mondiale

== L'espansione di Germania e Italia

L'espansione di Italia, Germania e Giappone scombinò gli equilibri in Europa, Hitler però non voleva fermarsi quì, perciò nel *1939* decide di *invadere la Polonia* occidentale subito dopo aver firmato il patto con la Russia (assicurandosi così che la Russia non avrebbe attaccato). Questa invasione diede inizio alla *Seconda guerra mondiale*. +
Pochi giorni dopo *Inghilterra e Francia* dichiarano guerra alla Germania. +
La Russia secondo l'accordo fatto con la Germania invade la parte orientale della Polonia, e per rafforzare i suoi confini occupa parte della Finlandia. +
Successivamente, nel 1940, Hilter occupa *Danimarca e Norvegia* con lo scopo di impadronirsi di materie prime e approvvigionamenti contro l'Inghilterra. +
Nello stesso anno la Germania decide di attaccare la Francia, per farlo invade Olanda, Belgio e Lussemburgo (che erano paesi neutrali) in modo da prendere alle spalle i francesi, riuscendoci con successo. +
Ora l'Inghilterra è rimasta da sola e Hilter programma di bombardare tutte le città inglesi, specialmente Londra, con l'intento di distruggere tutte le fabbriche di armi e costringerli alla resa. Gli inglesi non furono demoralizzati grazie al comando del primo ministro Winston Churchill, che con l'aiuto di radar (sconosciuti ad Hilter) e antiaeree riusci a infliggere alla Germania grandi perdite.

A questo punto l'Italia non era pronta ad una guerra dato che aveva mandato molte truppe in Etiopia e nella guerra in Spagna, perciò cerca di guadagnare tempo prima di entrare in guerra dichiarando la "non belligeranza" (termine usato per evitare di dire "neutralità" da Mussolini. Indica uno stato intermedio tra guerra e non intervento). +
*L'Italia entra in guerra nel 10 giugno del 1940* quando credeva che ormai la vittoria dei tedeschi era asscicurata, volendo un posto tra i vincitori.

Venne poi fatto un patto tra Italia, Germania e Giappone (e successivamente altre nazioni), il *patto tripartito* che puntava a creare un nuovo mondo con l'Europa comandata da Italia e Germania, e l'Asia sotto il controllo del Giappone. +
Poco dopo questo patto l'Italia subisce una sconfitta nel tantativo di occupare la Grecia, tentativo che invece andò a buon fine con l'aiuto della Germania. Successivamente l'Italia perse il controllo dell'Etiopia, Somalia ed Eritrea che passarono sotto il comando Inglese. +
Nuovamente solo grazie all'aiuto tedesco l'Italia riuscì a riconquistare i paesi che aveva perduto e nel 1942 riuscirono a conquistare parte d'Egitto. Tutte le spese delle azioni tedesche furono attribuite all'Italia.

Hitler ritenendo l'Inghilterra non capace di attaccare il dominio tedesco e vedendo la Russia come uno spazio vitale che dovrebbe appartenere alla Germania decide di *invadere l'Unione Sovietica* (22 giugno 1941). Seppur nei primi mesi la Germania riusciva ad avanzare, da lì a poco la situazione si sarebbe ribaltata a sfavore dei tedeschi: nel dicembre Mosca riesce a respingere l'attacco tedesco anche grazie all'arrivo dell'inverno gelido a cui i tedeschi non erano abituati.

Nel 7 dicembre 1941 entra in gioco anche il Giappone che con il desiderio di creare il proprio impero era consapevole che gli Stati Uniti avrebbero opposto resistenza, per cui il Giappone decisi di attaccare gli Stati Uniti, bombardando una base navale statunitense a sorpresa. Questo atto determina l'immediato *ingresso in guerra degli Stati Uniti*. +
Il Giappone che fino al 1942 era riuscito a conquistare moltissimi paesi iniziò a soffrire a causa delle rivolte anti-giapponesi fatte nei paesi conquistati. +
Gli Stati Uniti iniziarono una produzione di massa di armamenti che ben presto ribalterà la situazione mondiale.

== Massima espansione del regime nazifascista

Nel 1942 i paesi nazifascisti raggiunsero la loro massima espansione, la Germania che ormai aveva creato un grande impero voleva covincere l'europa a ritenere pericolosi i comunisti, i democratiti e gli ebrei, abolendo ogni libertà politica e ogni tipo di manifestazione di dissenso. +
La situazione peggiorò quando il compito di mantenere l'ordine nei paesi occupati venne dato alle SS che agirono con moltissima violenza, con un grande utilizzo dei *campi di concentramento* contro oppositori, politici, zingari, ebrei e omosessuali. Per gli ebrei le pene erano maggiori: 6 milioni di ebrei vennero uccisi nelle camere a gas, per realizzare il desiderio di genocidio di Hitler (olocausto).

== La resistenza

Iniziarono a diffondersi dei gruppi di resistenza contro il Nazismo e il Fascismo che in germania realizzarono degli attentati a Hitler ma senza successo, in Italia ci furono i *partigiani* che facevano una guerra per la liberazione dei nazisti ed una guerra civile contro gli italiani che sostenevano il nazifascismo. la resistenza era composta principalmente da comunisti, ma anche gli americani sostenevano questo movimento per fermare il nazifascismo, sia Russia che Stati Uniti però non volevano rafforzarsi tra di loro, essendo comunque rivali.

== La graduale sconfitta del regime nazifascista

Tra la fine del 1942 e l'inizio del 1943 si ebbero le prime sconfitte dell'impero tedesco (grazie all'entrata in guerra di Russia e soprattutto Stati Uniti), ci furono 3 battaglie principali: la battaglia aeronavale di Stati Uniti contro il Giappone per il controllo del Pacifico; la seconda battaglia si svolge in Africa: le truppe inglese sconfissero in Egitto l'esercito italo-tedesco e successivamente con il sostegno dei francesi costrinsero i tedeschi ad abbandonare l'Africa; la terza battaglia si svolse in Russia, a Stalingrado, in cui i Russi accerchiarono l'esercito tedesco e li costrinsero alla resa (questa fu la battaglia più dolorosa per Hitler).

Nonostante le sfiducie reciproche Stalin (Russia), Churchill (Regno Unito) e Roosevelt (Stati Uniti) si incontrano e decidono che gli anglo-americani sarebbero sbarcati in Normandia (nord della Francia). Lo *Sbarco in Normandia* si svolse nel Giugno del 1944 e fece affluire in Francia 1 milione e mezzo di uomini e moltissimi armamenti: loro riescono ad occupare la parte occidentale della Germania e la Russia quella Orientale, questo porta Hitler a suicidarsi e una settimanda dopo tutta la Germania si arrese.

== Fine della guerra in Giappone

Sebbene la guerra in europa era finita, in Giappone la situazione era ancora molto tesa. Il nuovo presidente degli Stati Uniti Truman decide di mettere fine alla guerra in Giappone sganciando due *bombe atomiche* sulle città di Hiroshima e Nagasaki. +
I vincitori della guerra furono così Stati Uniti, Gran Bretagna, Francia e Unione Sovietica. Questi paesi fecero un incontro per fare un processo contro i principali responsabili della guerra (*processo di Norimberga*).
