= Seconda guerra mondiale

L'espansione di Italia, Germania e Giappone scombinò gli equilibri in Europa, Hitler però non voleva fermarsi quì, perciò nel *1939* decide di *invadere la Polonia* occidentale subito dopo aver firmato il patto con la Russia (assicurandosi così che la Russia non avrebbe attaccato). Questa invasione diede inizio alla *Seconda guerra mondiale*. +
Pochi giorni dopo *Inghilterra e Francia* dichiarano guerra alla Germania. +
La Russia secondo l'accordo fatto con la Germania invade la parte orientale della Polonia, e per rafforzare i suoi confini occupa parte della Finlandia. +
Successivamente, nel 1940, Hilter occupa *Danimarca e Norvegia* con lo scopo di impadronirsi di materie prime e approvvigionamenti contro l'Inghilterra. +
Nello stesso anno la Germania decide di attaccare la Francia, per farlo invade Olanda, Belgio e Lussemburgo (che erano paesi neutrali) in modo da prendere alle spalle i francesi, riuscendoci con successo. +
Ora l'Inghilterra è rimasta da sola e Hilter programma di bombardare tutte le città inglesi, specialmente Londra, con l'intento di distruggere tutte le fabbriche di armi e costringerli alla resa. Gli inglesi non furono demoralizzati grazie al comando del primo ministro Winston Churchill, che con l'aiuto di radar (sconosciuti ad Hilter) e antiaeree riusci a infliggere alla Germania grandi perdite.

A questo punto l'Italia non era pronta ad una guerra dato che aveva mandato molte truppe in Etiopia e nella guerra in Spagna, perciò cerca di guadagnare tempo prima di entrare in guerra dichiarando la "non belligeranza" (termine usato per evitare di dire "neutralità" da Mussolini. Indica uno stato intermedio tra guerra e non intervento). +
*L'Italia entra in guerra nel 10 giugno del 1940* quando credeva che ormai la vittoria dei tedeschi era asscicurata, volendo un posto tra i vincitori.

Venne poi fatto un patto tra Italia, Germania e Giappone (e successivamente altre nazioni), il *patto tripartito* che puntava a creare un nuovo mondo con l'Europa comandata da Italia e Germania, e l'Asia sotto il controllo del Giappone. +
Poco dopo questo patto l'Italia subisce una sconfitta nel tantativo di occupare la Grecia, tentativo che invece andò a buon fine con l'aiuto della Germania. Successivamente l'Italia perse il controllo dell'Etiopia, Somalia ed Eritrea che passarono sotto il comando Inglese. +
Nuovamente solo grazie all'aiuto tedesco l'Italia riuscì a riconquistare i paesi che aveva perduto e nel 1942 riuscirono a conquistare parte d'Egitto. Tutte le spese delle azioni tedesche furono attribuite all'Italia.

Hitler ritenendo l'Inghilterra non capace di attaccare il dominio tedesco e vedendo la Russia come uno spazio vitale che dovrebbe appartenere alla Germania decide di *invadere l'Unione Sovietica* (22 giugno 1941). Seppur nei primi mesi la Germania riusciva ad avanzare, da lì a poco la situazione si sarebbe ribaltata a sfavore dei tedeschi: nel dicembre Mosca riesce a respingere l'attacco tedesco anche grazie all'arrivo dell'inverno gelido a cui i tedeschi non erano abituati.

Nel 7 dicembre 1941 entra in gioco anche il Giappone che con il desiderio di creare il proprio impero era consapevole che gli Stati Uniti avrebbero opposto resistenza, per cui il Giappone decisi di attaccare gli Stati Uniti, bombardando una base navale statunitense a sorpresa. Questo atto determina l'immediato *ingresso in guerra degli Stati Uniti*. +
Il Giappone che fino al 1942 era riuscito a conquistare moltissimi paesi iniziò a soffrire a causa delle rivolte anti-giapponesi fatte nei paesi conquistati. +
Gli Stati Uniti iniziarono una produzione di massa di armamenti che ben presto ribalterà la situazione mondiale.


