= Guerra civile spagnola

Negli anni del 1930 la Spagna viveva in un periodo di crisi profonda, per questo non partecipò nemmeno alla prima guerra mondiale, questa crisi era causata dalla guerra contro gli Stati Uniti nel 1898. +
La spagna non era un paese molto industrializzato ed era composta maggiormente da contadini, le terre erano in mano ai latifondisti e alla chiesa cattolica. Sostanzialmente il paese era controllato dai grandi proprietari terrieri, dalla chiesa e dall'esercito.

Nel 1931 ci furono le elezioni e vinsero coloro che volevano togliere la monarchia e introdurre una repubblica. Questo causò l'abbandono del re di spagna e delle preuccupazioni ai proprietari terrieri e alla chiesa. Proprio questi ultimi due riuscirono a conquistare il potere nelle elezioni del 1933 abolendo tutte le riforme che erano state fatte negli ultimi 2 anni. Nello stesso anno venne fondato un partito (di destra) che si ispirava al Fascismo chiamato "*La Falange*". +
Nel 1936 riprende il controllo di nuovo la sinistra reintroducendo la repubblica. +
A questo punto nascono delle faide tra sinistra (sostenuta da socialisti, comunisti, anarchici e borghesi tutti accomunati dall'odio per i grandi proprietari terrieri e la chiesa) e destra, di questa situazione approfitta l'esercito, sotto il controllo di *Francisco Franco* (che appoggiava "La Falange"), attaccando il governo attuale (repubblicano, di sinistra) e occupando la parte occidentale della Spagna instaurando un governo dittatoriale. +
La Spagna era divisa a metà: da una parte la repubblica e dall'altra una dittatura sotto il controllo della Falange.
Inizia così una guerra civile tra le due parti che durerà 3 anni (1936-1939). La sinistra che era sostenuta dalla Francia propose ai paesi europei di non intervenire nella battaglia interna (aderirono Inghilterra, Italia e Germania) per evitare che sostenessero La Falange. Questo accordo però fu infranto dall'Italia e dalla Germania che inviarono delle truppe in sostegno della Falange. +
La parte repubblicana invece fu sostenuta dal Messico e dall'Unione Sovietica, la potenza della falange era, però, troppo superiore e riuscirono a conquistare tutta la Spagna nel 1939. +
La dittatura durò fino alla morte di Francisco Franco (1975).
