= La caduta del Fascismo

Nel 1943 Gli Stati Uniti misero fuori gioco l'Italia con bombardamenti e conquistarono interamente la Sicilia. Questa occupazione smosse il governo: Vittorio Emanuele III (re d'Italia) fece imprigionare Mussolini, il 25 luglio del 1943, questa azione mise fine alla dittatura fascista, tutti i ritratti e i riferimenti a Mussolini sparsi per l'Italia vennero distrutti e le persone festeggiarono pensando che con la caduta del Fascismo anche la guerra sarebbe terminata. +
Questo però non accadde perchè venne sì fatto l'armistizio (tregua) con gli inglesi, ma la Germania sentendosi tradita mette in atto un'occupazione dell'Italia: il re e i principali comandanti fuggono al sud (sotto il comando degli inglesi) e il nord-italia viene occupato dai tedeschi, i soldati italiani vengono abbandonati dai loro superiori senza lasciar loro ordini. +
I tedeschi saccheggiarono tutto quello che c'era per spedirlo in Germania, obbligarono anche la Banca d'Italia a consegnare la riserva monetaria italiana (75 tonnellate d'oro) a Berlino. +
In questo momento in italia non funzionava la corrente elettrica, il gas era scarsissimo, molti servizi dello stato erano chiusi, non circolavano più automobili e camion. +
I tedeschi riuscirono a liberare Mussolini dalla prigione, il quale fonda la Repubblica Sociale Italiana chiamata *Repubblica di Salò*, dove nacque il nuovo governo fascista, con lo scopo di aiutare i tedeschi a fermare i partigiani italiani anti-fascisti.

La Resistenza italiana (*i partigiani*), a seguito della liberazione fatta dagli inglesi, si espanse: ex fascisti, soldati liberati dalla prigione con l'armistizio, persone che erano emigrate all'estero per sfuggire la guerra ma che sono ritornate; tutti si unirono alla resistenza sia militari che civili con il solo scopo di liberarsi del dominio nazifascista (da 4 mila membri si arrivò a circa 35 mila). +
Si forma così il *CNL* (Comitato di Liberazione Nazionale) di cui facevano parte tutti i partiti italiani, il cui obbiettivo era coordinare le operazioni dei partigiani. I partigiani erano divisi in brigate a seconda degli ideali politici dei membri. +
Con una buona coordinazione i partigiani riuscivano a scambiarsi informazioni, con le quali si riuscivano a scoprire gli spostamenti delle truppe tedesche, venivano così piazzete delle trappole esplosive per fermare i veicoli. +
Mussolini ormai senza più possibilità introduce la leva obbligatoria per i ragazzi dai 16 ai 19 anni, con la pena di morte per chi rifiutava. I ragazzi consapevoli che unirsi a mussolini sarebbe stato un suicidio comunque, decidono di unirsi ai partigiani e combattere al loro fianco, espandendo ancora di più il numero dei partecipanti.

Secondo la politica dei tedeschi per questa battaglia la morte di un soldato tedesco doveva corrispondere alla morte di 10 cittadini italiani, questa teoria si applico più volte durante quel periodo con la morte di migliaia di italiani.
