= Nascita della repubblica

Alla fine della guerra e dopo la scomparsa del partito Fascista la situazione politica in Italia era molto confusa e divisa tra *centro-nord*, in cui dominava la volontà di cambiamento, e *sud* in cui prevalevano le forze conservatrici.

In questo momento a sinistra c'erano i *comunisti* (PCI, Partito Comunista Italiano). Poi c'erano i socialisti che presero il nome di PSIUP (Partito Sociale Italiano di Unità Proletaria). +
Accanto a questi partiti si forma un nuovo partito: il *Partito d'Azione* (PdA) composto da intellettuali socialisti che avevano partecipato alla guerra di Spagna e sostenuto i partigiani nella liberazione dal Nazi-Fascismo. Questo partito non ha successo e i suoi votatori vanno o in PSIUP o nel *partito repubblicano* (PRI). +
Al centro c'era la *Democrazia Cristiana* (DC) che ottiene un discreto successo: infatti quel periodo viene chiamato "periodo del centrismo" proprio per la prevalenza di questo partito. +
Di destra c'era invece il *partito liberale italiano* (PLI) ispirato alla politica di Giolitti.

La *sinistra* era molto sostenuta dal popolo perchè i partiti presenti sono quelli che si sono più opposti al Fascismo. +
La *destra* era sostenuta dalle classi sociali più privilegiate, dagli americani a anche in parte dalla chiesa.

Il primo governo viene presieduto da Ferruccio Parri mentre il secondo da Alcide De Gasperi, entrambi questi governi nascono dalla forte collaborazione tra sinistra e centro-destra.

== 2 giugno 1946

Durante questo periodo ci furono *due grandi consultazioni popolari* che si tennero il *2 giugno del 1946*:

La prima è un referendum in cui si decideva se l'Italia doveva essere una *Monarchia o una Repubblica*. La votazione veniva data a tutti gli italiani (*anche le donne* per la prima volta). Il 54% votò Repubblica e il 46% Monarchia.

La seconda consultazione puntava a eleggere i deputati *dell'assemblea costituente* (formata da coloro il cui compito era elaborare la nuova Costituzione) che fissava i principi di libertà e di democrazia. La *Costituzione entra in vigore il 1 Gennaio 1948*. +
Una delle disposizioni della Costituzione vietava la riformazione del partito Fascista in ogni forma.  

Il partito più votato è la Democrazia Cristiana, e il presidente della Repubblica è *Enrico De Nicola*.

== Primo parlamento repubblicano

Nel 1948 ci furono delle elezioni per eleggiere il *primo parlamento* della nuova Repubblica, in queste elezioni era presente una forte contraddizione tra i cattolici (centro) e la sinistra. Grazie al fondamentale aiuto del papa (Pio XII) la democrazia cristiana riuscì a vincere. +
Dal 1948 al 1953 si succedettero tutti governi di centro con al comando Alcide De Gasperi, sostenuti dalla chiesa, dagli Stati Uniti e dagli industriali.

== Il miracolo economico

Dopo la morte di De Gasperi (1954) In Italia ci fu un periodo di prosperità economica, *il Miracolo economico*, che va da 1954 al 1963. +
In questo periodo l'Italia diventò un paese industrializzato e moderno, si sviluppa l'industria automobilistica, quella chimica, quella siderurgica, si sviluppano più elettrodomestici, l'abbigliamento. Furono costruite molte strade, nasce l'ENI (Ente Nazionale Idrocarburi). +
Cresendo il numero di industrie cresce anche il numero di operai e quindi la disoccupazione diminuisce. 

Erano comunque presenti sia immigrati che persone che andavano dal sud al nord per trovare lavoro, queste persone faticavano a parlare in Italiano. Vennero fatte, quindi, delle riforme al sistema scolastico: prima della riforma un bambino che terminava le elementari poteva scegliere tra la *scuola media* e la scuola per *l'avviamento al lavoro*, la prima ti preparava per proseguire gli studi (ma solo i privilegiati potevano andarci) mentre la seconda ti preparava al mondo del lavoro. +
Con la riforma si uniscono questi due indirizzi per formarne uno solo, perlopiù obbligatorio. 
