= Nascita della repubblica

Alla fine della guerra e dopo la scomparsa del partito Fascista la situazione politica in Italia era molto confusa e divisa tra *centro-nord*, in cui dominava la volontà di cambiamento, e *sud* in cui prevalevano le forze conservatrici.

In questo momento a sinistra c'erano i *comunisti* (PCI, Partito Comunista Italiano). Poi c'erano i socialisti che presero il nome di PSIUP (Partito Sociale Italiano di Unità Proletaria). +
Accanto a questi partiti si forma un nuovo partito: il *Partito d'Azione* (PdA) composto da intellettuali socialisti che avevano partecipato alla guerra di Spagna e sostenuto i partigiani nella liberazione dal Nazi-Fascismo. Questo partito non ha successo e i suoi votatori vanno o in PSIUP o nel *partito repubblicano* (PRI). +
Al centro c'era la *Democrazia Cristiana* (DC) che ottiene un discreto successo: infatti quel periodo viene chiamato "periodo del centrismo" proprio per la prevalenza di questo partito. +
Di destra c'era invece il *partito liberale italiano* (PLI) ispirato alla politica di Giolitti.

La *sinistra* era molto sostenuta dal popolo perchè i partiti presenti sono quelli che si sono più opposti al Fascismo. +
La *destra* era sostenuta dalle classi sociali più privilegiate, dagli americani a anche in parte dalla chiesa.

Il primo governo viene presieduto da Ferruccio Parri mentre il secondo da Alcide De Gasperi, entrambi questi governi nascono dalla forte collaborazione tra sinistra e centro-destra.

== Il boom economico

Dopo la dittatura in Italia vengono importate delle innovazioni e tipi di intrattenimento dall'America che erano negate quando c'era la dittatura.
Chewing gum, Coca Cola, abbigliamento, molti sport diventano più popolari ecc... Questo fece girare molto il commercio. Nascono i fotoromanzi, concorsi di moda come Miss Italia, nasce la SISAL per le scommesse sul Calcio. +
Questo portò una grande crescita economica dell'Italia: allargamento dei mercati, aumento dei salari, aumento dell'occupazione femminile e lo spostamento nelle città. 

== Nascita della Repubblica

Durante questo periodo ci furono *due grandi consultazioni popolari* che si tennero il *2 giugno del 1946*:

La prima è un referendum in cui si decideva se l'Italia doveva essere una *Monarchia o una Repubblica*. La votazione veniva data a tutti gli italiani (*anche le donne* per la prima volta). Il 54% votò Repubblica e il 46% Monarchia.

La seconda consultazione puntava a eleggere i deputati dell'assemblea costituente (formata da coloro il cui compito era elaborare la nuova Costituzione) che fissava i principi di libertà e di democrazia. La *Costituzione entra in vigore il 1 Gennaio 1948*. +
Una delle disposizioni della Costituzione vietava la riformazione del partito Fascista in ogni forma.  

Il partito più votato è la Democrazia Cristiana, e il presidente della Repubblica è *Enrico De Nicola*.
