= L'età giolittiana

Gli inizi del '900 furono caratterizzati da *Giovanni Giolitti*, un piemontese che aveva ideologie liberali (per cui da valore al singolo individuo).
Portò avanti il governo dal 1901 fino alla prima guerra mondiale.

== L'operato
Durante la sua carica riuscì a migliorare complessivamente l'amministrazione dello stato, e a favorire lo sviluppo del Nord, ignorando però le condizioni del Sud che considerava solamente come fonte di voti, favorendone la violenza. +
Per il Nord, invece, riuscì ad evitare l'uso della violenza sui movimenti popolari.

== Sindacati
Favorì la nascita dei sindacati, cioè quelle organizzazioni che fanno da intermediari tra i capi e gli operai, visto che li considerava il mezzo per regolare le proteste degli operai. +
Nasce quindi nel 1906 la *CGL*, la _Conferedazione Generale del Lavoro_ che aveva lo scopo di riunire i sindacati di ogni settore. +
Allo stesso tempo nasce anche la _Confindustria_, cioè la *Confederazione italiana dell'industria*.

== La politica con socialisti e cattolici
Per rendere più forte il suo governo cercò di fare alleanze anche con i partiti italiani avversari, che avano ideologie diverse. Non riuscendo a convincere completamente il partito socialista, si rivolse al partito dei cattolici che però fino ad all'ora si era astenuto dalla politica.

Il Papa finì per accettare l'accordo con Giolitti nel 1913 per cui, in base al *Patto Gentiloni*, l'_Unione Elettorale Cattolica_ si impegnava a votare per lui in cambio di una politica a favore dei cattolici. +
Grazie a loro *vinse* quindi le elezioni del 1913, che furono le prime con il suffragio universale maschile (cioè il _diritto a tutti_ i cittadini maschi di votare).

== La caduta
Con il suffragio finisce il periodo della destra e della sinistra storica, e comincia quello dei _partiti di massa_ perchè coinvolgono un gran numero di persone.

Spinto dai nazionalisti (la cui ideologia difendeva la patria), dai fabbricanti di armi e dai cattolici decise di *invadere* la Libia nel 1911. +
Visto che il governo non voleva affrontare i problemi economici, Giolitti decise di _ritirarsi_ dal governo.
