= Belle Époque

Dopo gli orrori causati dalla prima guerra mondiale, il periodo dell'anteguerra (_1910-1914_) venne riconsiderato come *un'epoca felice*.

== Borghesia
Questo pensiero si estendeva solo per le persone che, durante la preparazione alla guerra, riuscivano a vivere felici come se niente fosse. +
Principalmente erano *borgesi ricchi* che vivevano in condizioni privilegiate.

Per loro l'illusione era che il nuovo secolo fosse _l'inizio di un periodo di felicità_, anche grazie all'entusiasmo dato dagli avanzamenti tecnologici.

== Svago
Le città più frequentate erano:

* Parigi, che attraeva per i ristoranti e l'arte
* Vienna, che era il ritrovo dei ricchi

Divennero anche famosi i _casinò_, infatti Giolitti ne autorizzò l'apertura di uno in Italia.

Un'altra attrazione era *l'Orient Express*, che venne inaugurato nel 1863, con la _collaborazione tra più stati_. +
Era frequentato dai più ricchi internazionali, infatti diventò il *simbolo del lusso*.

Altre mode che si diffusero furono l'andare a teatro e i caffè dove, tra i tavolini, si _esibivano_ cantanti e musicisti.
