= La prima guerra mondiale

Ad inizio 1900 l'Europa era divisa in due blocchi: la *Triplice Alleanza* composta da Italia, Germania e Impero austro-ungarico e la *Triplice Intesa* composta da Inghilterra, Francia e Russia.

La situazione in quel periodo era molto delicata: la Germania voleva espandersi, l'Austria voleva delle colonie, i paesi balcanici (Albania, Serbia, Bulgaria, Grecia) avevano rivalità con Austria e Russia, i produttori di armi e i gruppi finanziari avevano i loro interessi da soddisfare, e infine la paura della triplice intesa nei confronti della Germania e Austria.

La scintilla che fece scoppiare la guerra fu l'*assassinio* dell'*erede al trono d'Austria* da parte di un serbo, che portò l'*Austria* ad *attaccare* la *Serbia*, la russia passa in difesa della serbia e la Germania in difesa dell'Austria. +
La *Germania dichiara guerra anche alla Francia* perchè faceva parte della triplice intesa. Per farlo invadono il Belgio, paese neutrale per i paesi europei per via dell'accordo con l'*Inghilterra* che la costrinse, con la sua potenza marittima, ad *attaccare la Germania*.

Con la *battaglia della Marna* i tedeschi furono costretti a fermarsi e iniziò una guerra di trincea con la Francia.

== Situazione italiana
A questo punto della guerra l'italia non era ancora intervenuta perchè la *triplice alleanza* era un patto *difensivo* e dato che è stata l'Austria ad attaccare per prima L'Italia non era obbligata a partecipare. +
l'Italia però voleva espandersi perciò firmò un accordo segreto (tradendo i propri alleati) con la triplice Intesa, il *Patto di Londra* del 1915. L'italia doveva entrare in guerra contro l'Austria e in cambio otteneva: Trento, Trieste, l'Istria e parte della Dalmazia. Anche tra Italia e Austria si formò una guerra di trincea.

== Entrata dell'America in guerra
Dopo che Francia e Germania fecero una tregua dichiarandosi entrambi vincitori, La *Germania attacca* con dei sottomarini delle *navi americane* che, di conseguenza, entrano in guerra. +
La *Russia si ritira* dalla guerra firmando un trattato di pace con la Germania perdendo Polonia, Estonia, Lettonia, Lituania e Finlandia. +
L'America entra in guerra a finaco di Francia, Inghilterra e Italia. Intanto l'Italia che stava perdendo contro l'Austria riusci ad ottenere una vittoria decisiva a Vittorio Veneto. A questo punto Austria e Germania si arrendono. L'Italia però *non ottiene i paesi promessi* dal Patto di Londra.