= La rivoluzione russa

All'inizio del 1900 la Russia era uno dei *paesi più popolati* del mondo e aveva una *grande quantità di risorse* naturali. La Russia però aveva una *pessima situazione sociale*: la maggioranza della popolazione era localizzata ad ovest (verso l'europa). La popolazione era divisa in Slavi, Polacchi, Turchi, Mongoli ecc... ognuno con lingua, cultura e religione diversa, Queste diverse etnie non andavano d'accordo tra loro. +
La Russia era comandata dallo *Zar* che deteneva il *potere assoluto* e utilizzava questo potere in maniera molto aggressiva (dispotismo): la stampa, i romanzi e libri venivano censurati; l'insegnamento nelle scuole veniva constantemente messo sotto sorveglianza; le persone nobili possedevano quasi tutte le terre rendendo la vita dei contadini intollerabile (fino a quando venne abolita la servitù della gleba che permise ai contadini di comprare del terreno); la ribellione non era mai una buona scelta. + 

I *borghesi lottavano per avere la costituzione*. +
Il *partito Social-democratico* (tutti con stessi diritti) era diviso in 2 correnti:

* *La corrente bolscevica* ("maggioranza") guidato la *Lenin* che sosteneva che fosse necessario lottare per ottenere una rivoluzione con la classe operaia al comando.
* *La corrente menscevica* ("minoranza") che sosteneva che prima di attuare rivoluzione bisognasse allearsi con i borghesi. +

Lo scontro di queste tre correnti di pensiero creano una situazione di malcontento e rabbia nella popolazione, che portano alla formazione dei *soviet*, cioè delle assemblee dove si riunivano gli esponenti di ogni paese per organizzare una protesta contro lo Zar. +
Lo Zar decise quindi di concedere la *Duma* (costituzione) e quindi l'elezione di un parlamento, ma stabilisce che il voto di un nobile equivale a quello di 1000 contadini.
